### ISSUE TITLE
Mandatory Yes/No Field

### ISSUE THREAD

**Issue by SoulOfSet** [bobintetley/asm3#1026]
**Describe the bug**
Mandatory 'Yes/No' type fields on forms do not fail validation if the user leaves it blank. 

**To Reproduce**
1. Open form with Yes/No checkbox that is mandatory
2. Do not select Yes or No
3. Submit form
4. Form is not rejected

**Expected behavior**
I would expect that the form would fail to validate with this Yes/No field set to mandatory. 

**Additional context**
I'm not sure whether or not this functionality was intentional? I wanted to get a confirmation on whether or not this was intentional or a bug? If there is agreement on if this is a bug I can fix it.

**Comment by bobintetley** [comment]
It's intentional. A checkbox can only have two states - what would mandatory mean to a checkbox?

**Comment by bobintetley** [comment]
also, to clarify are we talking online forms or additional fields on system screens? Yes/No is a checkbox for additional fields, but on online forms I think Yes/No is a dropdown with the two options and checkbox is a separate field type.

**Comment by SoulOfSet** [comment]
Sorry, let me clarify. I'm talking about Yes/No on the forms where it is a drop-down. The values available seem to be Blank/Yes/No. Leaving it blank does not trigger a failure on the validation if it is set to mandatory.

**Comment by SoulOfSet** [comment]
![image](https://user-images.githubusercontent.com/1868836/124691168-ff0b5b00-dea0-11eb-985c-addc8ee9e5df.png)

**Comment by SoulOfSet** [comment]
I went ahead and set up a PR for this as I won't be very available in the next few days. Of course, please decline if how it is working now is intended behavior. 

#1028

**Comment by bobintetley** [comment]
Thanks, I've merged it now. Since you've assigned the required attribute to the select when constructing the form, that's all that is needed - the dedicated yes/no handling in onlineform_extra.js is not necessary.

**Comment by SoulOfSet** [comment]
Ah my mistake. Misunderstood the flow there. Thanks
