### ISSUE TITLE
Import CSV: renumber animal codes

### ISSUE THREAD

**Issue by bobintetley** [bobintetley/asm3#1027]
When exporting animals as CSV, their shelter code is used as the ANIMALCODE column.

If the target database uses the same coding scheme, you could have the issue of code collision. This will cause the imported file to merge with the existing record instead of creating a new one. Offer an option to regenerate ANIMALCODEs. It will need to use a temporary dictionary to remember the codes in the file and what it has regenerated them to (obviously the first time, no entry in the dictionary triggers regeneration for that record, second time it will be in the dictionary).

**Comment by reutsharabani** [comment]
I would like to try and work on it. Any directions? Anyone has experience with how I can run and test this project on mac?

I can set up a virtual environment to use debian, but I think adding a way for mac can help other potential contributors as well.

If there is no experience with running it on mac I can try and add these as well.
