### ISSUE TITLE
Include subject in email document templates

### ISSUE THREAD

**Issue by bobintetley** [bobintetley/asm3#1088]
One user asked if it was possible to include a subject in document templates used for emails. 

They want to include a better description of (in this case) what someone is being requested to sign in the subject including things like the animal's name. Seems like a good idea to be able to do this generally. This mechanism wants to be generic and the angle bracket tokens need to work out without it even being noticed. 

Suggest the use of double curly braces since they will be ignored by wordprocessor.substitute_tags

{{SUBJECT <<AnimalName>> signing request}} 
{{FROM info@myshelter.com}}
{{CC person@myshelter.com}}
{{BCC person@myshelter.com}}

The code that handles templates for the emailform widget can then process the curly brace tags, where they will be ignored and become literal output in any other template.

**Comment by bobintetley** [comment]
Document in the manual under document templates. Mailmerge might have its own calls to generate templates.

**Comment by patgaytx** [comment]
I'm happy to test this when it's ready.

**Comment by bobintetley** [comment]
It makes no sense to allow the setting of the recipient fields from a template. {{FROM X}} is ok and {{SUBJECT X}}

**Comment by Tetzor** [comment]
Ticket complete.
