### ISSUE TITLE
Rewrite smartphone interface and merge mobile app

### ISSUE THREAD

**Issue by bobintetley** [bobintetley/asm3#1096]
The smartphone interface is built on JQuery mobile. This library has not been updated in many years and now looks dated.

The app is built on Bootstrap 3, which also looks dated. It has become increasingly difficult to deal with the nightmare that is app store deployments, constant demands for updating of keys or new features, etc. It costs us money to suffer the indignity of Apple making life virtually impossible and the office Mac has become virtually unusable with each update from Apple. On top of that, when users do have issues with the app, it's virtually impossible for us to recreate those problems and the turnaround time for fixes is SLOW. It's frustrating for customers and very frustating for us.

Rewrite the smartphone interface in Bootstrap. Merge the photo uploading feature from the app into it. 

Retire the app from all stores and direct users to m.sheltermanager.com with their mobile browser instead. 

Removing the login_jsonp target will effectively disable the app when the time comes. All of the code that looks for session.mobileapp to disable logout can be removed as well.

**Comment by bobintetley** [comment]
... and it's a nightmare every time there's an update from Cordova.

**Comment by patgaytx** [comment]
100% agree. Happy to test this one as well. Have both Android and iPhone.
