### ISSUE TITLE
Missing dependencies on Ubuntu focal (20.04)

### ISSUE THREAD

**Issue by mdziczkowski** [bobintetley/asm3#1184]
Hello. I wanted to let you know that Ubuntu has removed from it's official repositories for Ubuntu focal most of the packages that are required thru ASM3. Could you please try to find a fix for it to make it work?

It would be also nice from You if it were possible to reactivate the java version of it, to make ASM platform independant.

Thanks for your great work and have a nice day.

**Comment by bobintetley** [comment]
The dependencies list has already been updated for the next release (46), which will be released at the end of the year.
