### ISSUE TITLE
[sheltermanager.com] No access to a Linux reposiory URL

### ISSUE THREAD

**Issue by mdziczkowski** [bobintetley/asm3#1187]
Hello. I want to report a issue related to the sheltermanager.com website.

I attempted to access thru the web browser the URL given as the sheltermanager's Linux repostitory ("http://public.sheltermanager.com/deb/"), I had recieved the "Forbidden" error.

Please fix it. Thanks

**Comment by bobintetley** [comment]
Indexes being disabled is not an issue and it's certainly not a development issue for the program. Download the Packages.gz file if you want the list of packages/versions.
