### ISSUE TITLE
Create DB manually

### ISSUE THREAD

**Issue by mach37** [bobintetley/asm3#119]
hello, great app, I am having some trouble with the db creation. maint_db_install

- I am trying it, I am having trouble with the DB creation, can you please tell me which file creates the database,
- I would like to fork am trying to port to mongo, and sql express free, any pointers on where to start would help.
- Can you please add the just a regular `dbCreate.Sql` file,  or the output sql file to the repo here I [found this](https://github.com/magul/asm3/blob/ba16759586e825b0272e7f94ac8782c7040d756b/src/dbupdate.py), but I am not sure if thats the correct file

PS. I also see other repos with the same name, but they do not show a fork, looks like a copy

**Comment by bobintetley** [comment]
We don't maintain SQL scripts any longer as we support three different databases. The single dbupdate.py module generates the database script according to the value of sitedefs.DB_TYPE and executes it against the database.

If you want to support another database type, you'll need to add its driver to db.py as well as any specific type mappings in dbupdate.py

ASM relies on relational database features, so unless there exists a relational layer for Mongo (which I imagine would be either too basic or slow it down to the point it wasn't worth using) it would be an immense job trying to port it.

If you still want an SQL script, run an ASM install against an empty MySQL database and then use mysqldump to get the creation script from MySQL.

Good luck!

**Comment by mach37** [comment]
will ASM install on a windows machine? the requirements were not clear.

The SQL script is basic backbone of any app - for maintaining the app, hopefully someday you will.

**Comment by bobintetley** [comment]
We don't supply Windows installers, but if you can satisfy the main Python dependencies it's possible to run ASM on Windows (Python 2.7, web.py 0.37 or newer, Python Imaging Library).

**Comment by mach37** [comment]
I urgently need a way to create an empty DB, can you please share a MySql Db create script, I do not need compatibility, just a way to repopulate my excel data into ASM3.
