### ISSUE TITLE
ASM3 on ubuntu linux fails  , settings on wiki page are wrong

### ISSUE THREAD

**Issue by winecraft** [bobintetley/asm3#121]
Hey Bob thanks for the opp to try your software, while trying to install it failed for me and ran into some issues.

Installing on a Ubuntu Linux 16.04 LTS vanilla version failed for me, I even tried the following to use WSGI with Apache2 - there is an access problem accessing http://localhost/asm **"Forbidden Access"**

I will share some of what I found:

- [ ] 1. The http://localhost/asm "Forbidden Access" comes from the fact that Apache does not have ownership rights for execution on the [Dir where its installed](http://bit.ly/2iRGyI0)  _(as a suggestion why dont we move the install path to -> under var/www/asm this reduces the exposure and granting of all the rights), by the time we grant rights and ownership of usr/lib both the machine and user are  exposed to the vulnerabilities and execution rights from the internet._
- [ ] 2. A quick search inside [`sitedefs.ps`](https://github.com/bobintetley/asm3/blob/master/src/sitedefs.py) - reveals that these Variables/config settings do not exist in the previous file `ASM3_DBTYPE (POSTGRESQL, MYSQL or SQLITE) ASM3_DBHOST ASM3_DBPORT ASM3_DBUSERNAME ASM3_DBPASSWORD ASM3_DBNAME (can be sqlite3 file if type is SQLITE)` and the configuration file directions on the home page don't match the install
- [ ] 3. Can you please clarify if there is another setting for directory required in the apache2.config file to allow the directory /user/lib/sheltermanager
- [ ] 4. The db install failed with the current MySql install (MariaDb latest) the dbupdate.py file seriously needs a debug flag to output the Sql script to the text file - there were many exceptions. After rolling back to the older version I got it to install. _It would be nice to have a clean DB install without ASM2 compatibility for new installs_
- [ ] 5. What Ownership rights should be granted to Apache2 and on which Directories?
- [ ] 6. Is it possible to move the `default site config section for the directories` inside the VirtualHost Tag, the   `ServerName example.com ;  ServerAlias www.example.com ;  ServerAdmin username@example.com ;   DocumentRoot /var/www/html/example.com/public_html` are also missing based on the WSGI help page, can you add these so its complete the section

thanks
wine

**Comment by bobintetley** [comment]
Hi, 

1. /usr/lib/sheltermanager3 has global read and execute permissions? That should not be an issue. Apache should absolutely NOT have ownership of the directory as it should never write to it. Letting it do so could be a security risk.

2. I don't think I understand the question - those variables have always been there. Where are the instructions not matching? The instructions are in /usr/share/doc/sheltermanager3/README after install.

3. There should not need to be one, no. You should be able to just use WSGIScriptAlias /asm /usr/lib/sheltermanager3 - make sure you have libapache2-mod-wsgi installed and that it's enabled (a2enmod if Ubuntu is using the same Apache packaging as Debian).

4. That does sound serious, could you give me some of the errors you're seeing?

5. Apache2 should not have any ownership of sheltermanager directories.

6. I don't think WSGIScriptAlias and any of the mod_wsgi stuff can be put inside a VirtualHost tag - it's all global as WSGIScriptAlias loads a process pool of the application in an embedded Python interpreter. You can use multiple occurences of WSGIDaemonProcess and WSGIScriptAlias in an Apache config to declare multiple WSGI programs with their own names though. I'd check out the mod_wsgi docs for more info.

mod_wsgi and Apache are complex topics in their own right though. You don't need mod_wsgi to run ASM, you can just run it in its own webserver with "cd /usr/lib/sheltermanager3 && python code.py 5000" to start the embedded webserver on port 5000.

If you run ASM this way, the current console will be connected to the application and if you go through the database startup, all the SQL and errors will be logged to the console.

Thanks for your interest in ASM!
