### ISSUE TITLE
incorrect date time value

### ISSUE THREAD

**Issue by rementis** [bobintetley/asm3#1225]
Jan 31 11:08:12 lightningtournament CRITICAL asm    Database.query                 (1525, "Incorrect DATETIME value: ''2023-01-31 06:25:36''") File "/usr/lib/sheltermanager3/asm3/dbms/base.py", line 552, in query#012    s.execute(sql, params) File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 209, in execute#012    res = self._query(query) File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 315, in _query#012    db.query(q) File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 239, in query#012    _mysql.connection.query(self, query) MySQLdb._exceptions.OperationalError: (1525, "Incorrect DATETIME value: ''2023-01-31 06:25:36''")

**Comment by bobintetley** [comment]
Cannot reproduce with MariaDB 10.6.11
