### ISSUE TITLE
FTP timeout too short for PetFinder

### ISSUE THREAD

**Issue by inghamn** [bobintetley/asm3#1280]
Publishing to PetFinder has been failing for us for a while, now.  I upgraded to the latest source release and have the same error.  The error reported in the log is that the FTP socket timed out.  When I manually FTP to PetFinder, using our credentials, the inital login takes 30-45 seconds, sometimes more.

The timeout is currently hard-coded to 15 seconds in publishers/base.py.  We changed the code to 60 seconds and were able to upload to PetFinder.

Would this be something worth making part of the configuration file?

**Comment by bobintetley** [comment]
Thanks, yes, makes sense. I've made the default 60s if not supplied in the conf file. Sounds like PetFinder need a more powerful FTP server to cope with the volumes they're receiving.
