### ISSUE TITLE
Ansible: split ansible deployment into a seperate repository

### ISSUE THREAD

**Issue by inghamn** [bobintetley/asm3#1302]
The ansible deployment script has many decisions hard coded that are the practice for a single city.  I do not have a sense of whether this is useful for other citys' deployments, or not.  If desired, it would be relatively easy to split the ansible deployment scripts out into a seperate Github repo.

**Comment by bobintetley** [comment]
It could make sense, I've used other projects that keep ansible separate from the mainline. I think this might be more of an issue if we had more Ansible users, but I think you might be the only one!

**Comment by inghamn** [comment]
I am happy to defer to your preference on whether to keep Ansible scripts in the mainline, or not.  I do seem to be the only one updating them.  It would be trivial for me to push to a different repo.

I do not consider the current Ansible deployment very flexible - it does not provide for all the possible ways someone could want to deploy ASM.  Most of the decisions hard coded in the scripts are made based on how our city deploys it.

Maybe our city's decisions reflect the best practices.....er...maybe not, I don't know.

**Comment by bobintetley** [comment]
I'd probably keep them in, they aren't very big and it saves faffing around with another repo. In my opinion that the point of tools like Ansible is to give you a quick way to get a piece of software deployed, by nature it should be making most of the decisions for you so I don't see that as an issue?

**Comment by inghamn** [comment]
Fair enough, I am happy to continue pushing Ansible deployment changes upstream.
