### ISSUE TITLE
Owned Animals by Address

### ISSUE THREAD

**Issue by bobintetley** [bobintetley/asm3#1340]
Report where the user enters a street address as criteria, the report finds all people who live at that address, groups by person and lists all the animals they own - use animal.OwnerID to link between them (requires db update 34404).

Use case is when shelters get a report of an animal loose on a street, they can try and find a possible owner.

Include basic info about the animal - sex, age, size, breed, species

**Comment by bobintetley** [comment]
also include full contact info for the owner

**Comment by Tetzor** [comment]
reported created and added to repository.
