### ISSUE TITLE
Active sponsors mail merge

### ISSUE THREAD

**Issue by bobintetley** [bobintetley/asm3#170]
Add a new mail merge called "Active sponsors" that identifies all sponsors (people who have made a payment of type "%Sponsorship%" in the last month) along with details of the animal they are sponsoring. Include the following fields:

DISTINCT OwnerName, OwnerForeNames, OwnerSurname, OwnerAddress, OwnerTown, OwnerCounty, OwnerPostcode, EmailAddress, AnimalName, ShelterCode, BreedName, SpeciesName

**Comment by Tetzor** [comment]
Added mail merge "Donors between two dates for type" with selectable payment type and date range.
