### ISSUE TITLE
Search result returning blank results

### ISSUE THREAD

**Issue by mikewschmidt** [bobintetley/asm3#184]
![screenshot from 2017-03-23 17-22-22](https://cloud.githubusercontent.com/assets/15319471/24272943/bfafdd5e-0fed-11e7-8f6e-de34817bcdd9.png)

**Comment by bobintetley** [comment]
It looks like you don't have any columns configured for find animals. I've checked your database and half your config table has been overwritten with junk. I can't explain how or why this is happened, but I've reset it now so everything should be back to normal now. You may need to log out and back in again.

github issues are for software bugs and developers, please contact us directly for support in future at  support@sheltermanager.com
