### ISSUE TITLE
v_animal View is very slow

### ISSUE THREAD

**Issue by inghamn** [bobintetley/asm3#206]
The prepared report for "Adoptable Animals" is very slow for us.  It takes about 3 minutes to return only 50 animals.  The problem is with the definition of the view that it is reading from.

Replacing the report's SQL with a query against the master tables, instead of the view eliminates the performance problem.  It might be worth redefining the view with a more performant definition.

```sql
select  a.ID          as AnimalID,
        a.ShelterCode,
        a.AnimalName,
        a.BreedName,
        sz.Size       as SizeName,
        sx.Sex        as SexName,
        a.AnimalAge,
        a.TimeOnShelter,
        if (a.Neutered,           'Yes', 'No') as NeuteredName,
        if (a.IsGoodWithCats,     'Yes', 'No') as IsGoodWithCatsName,
        if (a.IsGoodWithDogs,     'Yes', 'No') as IsGoodWithDogsName,
        if (a.IsGoodWithChildren, 'Yes', 'No') as IsGoodWithChildrenName,
        if (a.IsHouseTrained,     'Yes', 'No') as IsHouseTrainedName,
        a.DisplayLocation,
        a.AnimalComments,
        sp.SpeciesName
from animal a
left join lksize  sz on a.Size      = sz.ID
left join lksex   sx on a.Sex       = sx.ID
left join species sp on a.SpeciesID = sp.ID
where Archived = 0
  and IsNotAvailableForAdoption = 0
  and HasTrialAdoption = 0
order by SpeciesName, AnimalName
```

**Comment by bobintetley** [comment]
Thanks, we have a policy of not using v_animal for repository reports but somehow that one has snuck in. I've used your replacement SQL in the repository now and updated, thanks again.
