### ISSUE TITLE
database refactoring

### ISSUE THREAD

**Issue by bobintetley** [bobintetley/asm3#230]
After discussions with Davy on DB refactoring:

1. Create a new "db" package to move db.py into. 
2. Rename DatabaseInfo() object to Database()
3. For each DB provider, make a new db_mysql.py, db_sqlite.py etc, containing a subclass of Database() with all database specifics in.
4. Move all the db.py functions (connection, query, execute, etc) into the base Database() class so they can be overridden in subclasses where needed
5. Move dbupdate.shorttext, longtext, datetype, add_column, add_index, create_table, create_view, etc into the DB subclass so that code can call it in dbo to figure what types to use. This simplifies dbupdate a lot as it can call dbo without having to know which type of backend it's dealing with.
6. Make limit a parameter passed to query and execute instead of something in SQL. Have a limit() function that writes the SQL that the base class can call.
7. Make the existing functions in db.py call the dbo methods for now so existing code is compatible.
8. Look to move toward prepared statements.
9. Fix everywhere that instanties DatabaseInfo to call a new method in db.py that instanties the correct object based on the DBTYPE sitedef. smcom can create DatabasePostgreSQL without having to check.

**Comment by davydnorris** [comment]
Exciting!

Regarding 9 - could we override the constructor for the DatabaseInfo superclass so that it constructs and returns the appropriate subclass? Then you won't have to change any code.

**Comment by bobintetley** [comment]
Unfortunately, that's not possible with Python classes. All we can do is either have a module method to do it (the proposal here) or a static factory method on DatabaseInfo. I prefer the former because it keeps the base class neater and without it having to have knowledge of its subclasses.

**Comment by davydnorris** [comment]
Factory method is next best thing anyway - just as good as a bought one :-)

**Comment by bobintetley** [comment]
Next task is to rewrite make_*_sql methods as Database.insert and Database.update using parameterised statements. Need to consider how XSS escaping is to be done (simplest way might be an optional third parameter to disable xss escaping on strings if present - otherwise it's automatic if the parameter value is a string)

**Comment by davydnorris** [comment]
OK I've now written db2.py - very neat with the new structure!

While doing that I noticed update_asm2_primarykey uses a delete and insert - couldn't it just use:
'''
"UPDATE primarykey SET NextID = %s WHERE TableName = '%s'" % (nextid, table)
'''

**Comment by bobintetley** [comment]
It's that the row isn't guaranteed to be there. I think we had an UPSERT type thing at one point and it was changed for clarity. To be honest, that routine is deprecated and very few people have that option turned on as it's off by default and only of use if you're using ASM2 and 3 on the same database at the same time.

**Comment by bobintetley** [comment]
further issue: get_animal_query has a LIKE %jpg in it which blows up parameterised queries when going through animal_find_simple. Ideally, have a MediaExtension column to split up filename (with dbupdate) so that the comparison can be done without pattern matching and via an index on MediaExtension for performance.

**Comment by davydnorris** [comment]
Noticed the code uses execute instead of prepare then execute. I know DB2 will optimise and cache statements if you use the prepare method first, and then execute. This would offer potential performance improvements, especially in executing the most common statements

**Comment by bobintetley** [comment]
I think that's the python DBAPI - as far as I'm aware there isn't a separate prepare step and it's all done in cursor.execute?

**Comment by davydnorris** [comment]
actually you're right - just looked at the db2 port and ibm_db_dbi.execute() does
`       self._prepare_helper(operation)
        self._set_cursor_helper()
        self._execute_helper(parameters)
        return self._set_rowcount()
`

**Comment by bobintetley** [comment]
moving to a new refactoring issue for milestone 41. compatibility work is done, rewriting to use prepared statements is a slow next step.
