### ISSUE TITLE
Regression?? - redirect to database doesn't seem to be happening if db is empty

### ISSUE THREAD

**Issue by davydnorris** [bobintetley/asm3#237]
For some reason if you go to any page other than the root (so eg. <server>/login instead of <server>/) and your database isn't configured, it is throwing errors instead of taking you to the database page.

If you specifically go to the root http://<server>/ it works.

**Comment by bobintetley** [comment]
It's always done that. I don't think that's a regression - there's only / that redirects to /database if the database is unconfigured. Other targets don't and throw errors instead.

**Comment by davydnorris** [comment]
ok then that's consistent with what i'm seeing. I thought it used to redirect - been a while though
