### ISSUE TITLE
Zero byte PDF downloads

### ISSUE THREAD

**Issue by detheridge02** [bobintetley/asm3#254]
Hi, we've been using ASM for a couple of years for our rescue charity and find it a fantastic system that has streamlined the work we do and therefore has allowed us to concentrate on rescuing more dogs. 

Recently when we download PDFs we are getting zero byte files returned. Non-PDF files download correctly. 

The main version we use is 35 but I have also tested this on version 39 as I'm looking to upgrade to a more recent version.
The Python version are 2.7.6 for the version 35 installation and version 2.7.9 on the version 39 installation. The same issue occurs whether ASM is started as a service or provisioned via Apache and mod_wsgi.

Thanks in advance for any help

**Comment by detheridge02** [comment]
An additional note, this occurs in all browsers.

**Comment by bobintetley** [comment]
Turn off PDF scaling in the sitedefs if you can immediately.

There was a really nasty bug in an older version around the time of 35 that meant that if you didn't have a suitable piece of software installed to do PDF scaling (possibly imagemagick or ghostscript depending on version - that's also configured in sitedefs as SCALE_PDF_CMD), your PDF files would be overwritten with 0 bytes files. I really hope you have backups.

To fix it either, upgrade or turn off PDF scaling in sitedefs, but I'm afraid that any existing PDFs that were attempted to be scaled will have been trashed and replaced with a zero byte file.

Make sure SCALE_PDF_DURING_ATTACH and SCALE_PDF_DURING_BATCH are False.

**Comment by detheridge02** [comment]
I've set these and PDFs are now working correctly. Thanks for your quick response
