### ISSUE TITLE
Signature on tablet stopped working

### ISSUE THREAD

**Issue by Bambiemurphy** [bobintetley/asm3#258]
Since the last update signatures on tablets will not work.

**Comment by bobintetley** [comment]
How are you using signatures? Is it via the desktop "sign on screen"? Are you using the sheltermanager app or a particular web browser on your tablet? What make/OS is your tablet? This sounds like it could be related to the other problem you reported, please drop us an email support@sheltermanager.com with more info.

**Comment by Bambiemurphy** [comment]
Via tablet "sign on screen" The app. 

Asus P023
Android version 5.0.2

I have no issues with it on my own personal Ipad. It seems to be an issue with the save command.
