### ISSUE TITLE
Person search locks the database

### ISSUE THREAD

**Issue by inghamn** [bobintetley/asm3#263]
The simple person search, when running on MySQL locks the database for 10 minutes or so.

We're running version 39, and I don't know if #231 fixed this.  We need to figure out a way to make this query run in under a second.

![screen](https://user-images.githubusercontent.com/630282/28584749-da34c6e4-713b-11e7-82da-18f3092f7a66.png)

```sql
SELECT DISTINCT o.*, o.ID AS PersonID,
        ho.OwnerName AS HomeCheckedByName,
        ho.HomeTelephone AS HomeCheckedByHomeTelephone,
        ho.MobileTelephone AS HomeCheckedByMobileTelephone,
        ho.EmailAddress AS HomeCheckedByEmail, web.MediaName AS WebsiteMediaName, web.Date AS WebsiteMediaDate, web.MediaNotes AS WebsiteMediaNotes,
        (SELECT COUNT(oi.ID) FROM ownerinvestigation oi WHERE oi.OwnerID = o.ID) AS Investigation,
        (SELECT COUNT(ac.ID) FROM animalcontrol ac WHERE ac.OwnerID = o.ID OR ac.Owner2ID = o.ID or ac.Owner3ID = o.ID) AS Incident
FROM owner o
LEFT OUTER JOIN owner ho ON ho.ID = o.HomeCheckedBy
LEFT OUTER JOIN media web ON web.LinkID = o.ID AND web.LinkTypeID = 3 AND web.WebsitePhoto = 1 
WHERE (
    ((LOWER(o.OwnerName) LIKE '%bloomington%' OR LOWER(o.OwnerName) LIKE  '%bloomington%'))
    OR LOWER(o.OwnerCode) LIKE '%bloomington%'
    OR LOWER(o.OwnerCode) LIKE  '%bloomington%'
    OR LOWER(o.OwnerAddress) LIKE '%bloomington%'
    OR LOWER(o.OwnerAddress) LIKE  '%bloomington%'
    OR LOWER(o.OwnerTown) LIKE '%bloomington%'
    OR LOWER(o.OwnerTown) LIKE  '%bloomington%'
    OR LOWER(o.OwnerCounty) LIKE '%bloomington%'
    OR LOWER(o.OwnerCounty) LIKE  '%bloomington%'
    OR LOWER(o.OwnerPostcode) LIKE '%bloomington%'
    OR LOWER(o.OwnerPostcode) LIKE  '%bloomington%'
    OR LOWER(o.EmailAddress) LIKE '%bloomington%'
    OR LOWER(o.EmailAddress) LIKE  '%bloomington%'
    OR LOWER(o.HomeTelephone) LIKE '%bloomington%'
    OR LOWER(o.HomeTelephone) LIKE  '%bloomington%'
    OR LOWER(o.WorkTelephone) LIKE '%bloomington%'
    OR LOWER(o.WorkTelephone) LIKE  '%bloomington%'
    OR LOWER(o.MobileTelephone) LIKE '%bloomington%'
    OR LOWER(o.MobileTelephone) LIKE  '%bloomington%'
    OR LOWER(o.MembershipNumber) LIKE '%bloomington%'
    OR LOWER(o.MembershipNumber) LIKE  '%bloomington%'
    OR EXISTS(
        SELECT ad.Value
        FROM additional ad
        INNER JOIN additionalfield af ON af.ID = ad.AdditionalFieldID AND af.Searchable = 1
        WHERE ad.LinkID=o.ID AND ad.LinkType IN (1, 7, 8) AND LOWER(ad.Value) LIKE '%bloomington%'
    )
)
ORDER BY o.OwnerName LIMIT 100

```

**Comment by inghamn** [comment]
Removing the IncidentCount got it down to 20 seconds, instead of 10 minutes.  But 20 seconds is still kinda slow for a quick person search.

**Comment by bobintetley** [comment]
Where's IncidentCount? It's not in get_person_query or get_animal_query
for the latest codebase. Are you working off an older version?

**Comment by bobintetley** [comment]
That's weird, I wonder why the incident count takes so long? There are indexes on ac.Owner/2/3/ID.

#231 certainly should help as well - try removing DISTINCT from person.py/get_person_query to see if it improves things for you.

#230 also should help as searches are being rewritten to use parameterised statements (and a future task is to consider fulltext instead).

**Comment by inghamn** [comment]
We are running release 39.  The master branch doesn't seem like it would be stable right now.  We're definitely looking forward to release 40, when it's ready.

Removing the distinct got it down to about 4 seconds.  The  Incident count is definitely slow, with no key being used.  Here's the explain:

```txt
+----+--------------------+-------+------------+--------+---------------------------------------------------------------------+----------------------------+---------+---------------------+-------+----------+-----------------------------------------------------+
| id | select_type        | table | partitions | type   | possible_keys                                                       | key                        | key_len | ref                 | rows  | filtered | Extra                                               |
+----+--------------------+-------+------------+--------+---------------------------------------------------------------------+----------------------------+---------+---------------------+-------+----------+-----------------------------------------------------+
|  1 | PRIMARY            | o     | NULL       | index  | NULL                                                                | owner_OwnerName            | 767     | NULL                |    65 |   100.00 | Using where; Using temporary                        |
|  1 | PRIMARY            | ho    | NULL       | eq_ref | PRIMARY                                                             | PRIMARY                    | 4       | asm.o.HomeCheckedBy |     1 |   100.00 | NULL                                                |
|  1 | PRIMARY            | web   | NULL       | ref    | media_LinkID,media_LinkTypeID,media_WebsitePhoto                    | media_LinkID               | 4       | asm.o.ID            |     1 |   100.00 | Using where                                         |
|  4 | DEPENDENT SUBQUERY | af    | NULL       | ALL    | PRIMARY                                                             | NULL                       | NULL    | NULL                |    18 |    10.00 | Using where                                         |
|  4 | DEPENDENT SUBQUERY | ad    | NULL       | range  | additional_LinkTypeIDAdd,additional_LinkTypeID                      | additional_LinkTypeIDAdd   | 4       | NULL                |   725 |     1.00 | Using where; Using join buffer (Block Nested Loop)  |
|  3 | DEPENDENT SUBQUERY | ac    | NULL       | ALL    | animalcontrol_OwnerID,animalcontrol_Owner2ID,animalcontrol_Owner3ID | NULL                       | NULL    | NULL                | 58063 |    27.10 | Range checked for each record (index map: 0x380000) |
|  2 | DEPENDENT SUBQUERY | oi    | NULL       | ref    | ownerinvestigation_OwnerID                                          | ownerinvestigation_OwnerID | 4       | asm.o.ID            |     1 |   100.00 | Using index                                         |
+----+--------------------+-------+------------+--------+---------------------------------------------------------------------+----------------------------+---------+---------------------+-------+----------+-----------------------------------------------------+
7 rows in set, 6 warnings (0.00 sec)

```

**Comment by inghamn** [comment]
So, even with the DISTINCT removed, we're still seeing query times for people searches around a minute long.  Would it break anything to remove the Incident count portion?

```
# Time: 2017-07-26T15:40:41.810026Z
# User@Host: asm[asm] @ localhost []  Id:  4438
# Query_time: 58.175943  Lock_time: 0.001398 Rows_sent: 1  Rows_examined: 40333833
```

**Comment by bobintetley** [comment]
It will break the warnings on the movement and adoption screens that a person has previous incidents against them. Looks like you have rather a lot of incident records. Could you verify that you've got indexes on the three ownerid fields of animalcontrol?

**Comment by bobintetley** [comment]
actually, they're there in the possible_keys list, wonder why they aren't being used?

**Comment by inghamn** [comment]
We have 54,210 rows in owner and 61,742 rows in animalcontrol.  Our records go back to 2005.

**Comment by inghamn** [comment]
Does the person search screen *have* to use the same query as the movement and adoption screens?  The movement and adoption screens are working with a single owner or animal.

If we wanted to tackle having the search forms call a different query, how many places would we need to update?

**Comment by inghamn** [comment]
Our users are reporting that they removed a searchable additional field from the load and found animal screens and saw drastically improved performance.  I have not been able to confirm the performance improvement, but it's possible.

**Comment by bobintetley** [comment]
It'd be just person_find_simple and person_find_advanced. Before falling back to separate search queries (and don't forget that person find columns can be configured so we'd still need the same columns), there are a couple of things we could try to see if we can fix the performance of the person incident flag on MySQL.

First, try a composite key on all 3 owner id fields:

CREATE INDEX animalcontrol_Owner3 ON (OwnerID, Owner2ID, Owner3ID)

Next, we could try rewriting the query to use an exists construct, so instead of:

(SELECT COUNT(oi.ID) FROM ownerinvestigation oi WHERE oi.OwnerID = o.ID) AS Investigation,
(SELECT COUNT(ac.ID) FROM animalcontrol ac WHERE ac.OwnerID = o.ID OR ac.Owner2ID = o.ID or ac.Owner3ID = o.ID) AS Incident 

Let's try:

CASE WHEN EXISTS (SELECT OwnerID FROM ownerinvestigation WHERE OwnerID = o.ID) THEN 1 ELSE 0 END AS Investigation,
CASE WHEN EXISTS(SELECT OwnerID FROM animalcontrol WHERE OwnerID = o.ID OR Owner2ID = o.ID OR Owner3ID = o.ID) THEN 1 ELSE 0 END AS Incident

**Comment by inghamn** [comment]
That doesn't alter the query plan.  It's still doing a range check for every owner row.  If you're only wanting to know if the owner has one or more incidents, and don't care about how many, we could join the animalcontrol table and check for null.

I was thinking it was important for your query to know the count.  If the count is not important, then doing it as a join returns in microseconds:

```sql
SELECT  o.*, o.ID AS PersonID,
        ho.OwnerName AS HomeCheckedByName,
        ho.HomeTelephone AS HomeCheckedByHomeTelephone,
        ho.MobileTelephone AS HomeCheckedByMobileTelephone,
        ho.EmailAddress AS HomeCheckedByEmail, web.MediaName AS WebsiteMediaName, web.Date AS WebsiteMediaDate, web.MediaNotes AS WebsiteMediaNotes,
        CASE WHEN EXISTS(SELECT OwnerID FROM ownerinvestigation WHERE OwnerID = o.ID) THEN 1 ELSE 0 END AS Investigation,
        case when (ac1.ID is null and ac2.ID is null and ac3.ID is null) then 0 else 1 end as Incident
FROM owner o
LEFT OUTER JOIN owner ho ON ho.ID = o.HomeCheckedBy
LEFT OUTER JOIN media web ON web.LinkID = o.ID AND web.LinkTypeID = 3 AND web.WebsitePhoto = 1 
left join animalcontrol ac1 on o.ID=ac1.OwnerID
left join animalcontrol ac2 on o.ID=ac2.Owner2ID
left join animalcontrol ac3 on o.ID=ac3.Owner3ID
WHERE (
    ((LOWER(o.OwnerName) LIKE '%bloomington%' OR LOWER(o.OwnerName) LIKE  '%bloomington%'))
    OR LOWER(o.OwnerCode) LIKE '%bloomington%'
    OR LOWER(o.OwnerCode) LIKE  '%bloomington%'
    OR LOWER(o.OwnerAddress) LIKE '%bloomington%'
    OR LOWER(o.OwnerAddress) LIKE  '%bloomington%'
    OR LOWER(o.OwnerTown) LIKE '%bloomington%'
    OR LOWER(o.OwnerTown) LIKE  '%bloomington%'
    OR LOWER(o.OwnerCounty) LIKE '%bloomington%'
    OR LOWER(o.OwnerCounty) LIKE  '%bloomington%'
    OR LOWER(o.OwnerPostcode) LIKE '%bloomington%'
    OR LOWER(o.OwnerPostcode) LIKE  '%bloomington%'
    OR LOWER(o.EmailAddress) LIKE '%bloomington%'
    OR LOWER(o.EmailAddress) LIKE  '%bloomington%'
    OR LOWER(o.HomeTelephone) LIKE '%bloomington%'
    OR LOWER(o.HomeTelephone) LIKE  '%bloomington%'
    OR LOWER(o.WorkTelephone) LIKE '%bloomington%'
    OR LOWER(o.WorkTelephone) LIKE  '%bloomington%'
    OR LOWER(o.MobileTelephone) LIKE '%bloomington%'
    OR LOWER(o.MobileTelephone) LIKE  '%bloomington%'
    OR LOWER(o.MembershipNumber) LIKE '%bloomington%'
    OR LOWER(o.MembershipNumber) LIKE  '%bloomington%'
    OR EXISTS(
        SELECT ad.Value
        FROM additional ad
        INNER JOIN additionalfield af ON af.ID = ad.AdditionalFieldID AND af.Searchable = 1
        WHERE ad.LinkID=o.ID AND ad.LinkType IN (1, 7, 8) AND LOWER(ad.Value) LIKE '%bloomington%'
    )
)
ORDER BY o.OwnerName LIMIT 100
```

**Comment by bobintetley** [comment]
Nowhere in the system cares how many incidents, they just care whether that value is > 0. I think rewriting the Incident and Investigation flags to use JOINs instead is a perfectly acceptable solution and I'll put this into the trunk. 

Interestingly, we don't see any such problems on much larger databases with PostgreSQL.

**Comment by inghamn** [comment]
I think we can chalk this up to quirks in the database servers.

Subqueries in MySQL have always been slow.  MySQL's manual recommends using joins instead of subqueries as a performance imrpovement.  I'm sure Postgres has better optimization for subqueries.  ASM's dependence on subqueries for so many database interactions probably means it runs much slower in MySQL than Postgres.

https://dev.mysql.com/doc/refman/5.7/en/rewriting-subqueries.html
https://dev.mysql.com/doc/refman/5.7/en/subquery-optimization.html

**Comment by bobintetley** [comment]
Well, without getting into holy wars I think Postgres has pretty much better everything! :)

**Comment by bobintetley** [comment]
P.S. Thanks for your work!

**Comment by inghamn** [comment]
Thanks so much for looking into it.  Here, in Bloomington, we might go ahead and redeploy with Postgres.
