### ISSUE TITLE
Form tab under animal/contact

### ISSUE THREAD

**Issue by nellanaesp** [bobintetley/asm3#278]
This is just a suggestion for improvement. It would be very nice to have a separate tab under an animal or a contact that forms are dropped in, rather than under the 'media' tab. We have pictures, vet records, etc. under the media tab and it gets cluttered. Maybe just a list of all attached forms to the animal/contact and a link to open them, rather than the way it's presented in the media? 

We'd like to use ASM as our adoption application manager, but with the way it is currently, it is hard to keep track of attached applications to dogs since everything is dropped under the media tab. 

Thanks!

**Comment by bobintetley** [comment]
That's a really good idea and something worth considering. Storing forms in media means they lose versioning via our database backups as well and it would be great to reconsider form storage. At the same time, I think it might also be a good idea to have the option to view the media tab as a sortable list (I'm sure we have an issue to look at that already).

**Comment by nellanaesp** [comment]
Excellent! Even a folder type hierarchy underneath the media tab would be a great improvement, where we can move things into named folders, like 'medical' or 'pictures' or 'applications'.

**Comment by bobintetley** [comment]
the task to present media as a list was done quite a while ago and enables items of the same type to be grouped together.
