### ISSUE TITLE
Adding Payment

### ISSUE THREAD

**Issue by Bambiemurphy** [bobintetley/asm3#300]
When adding a payment to an account I get this error

No source account found for donation type, can't create trx
![source account](https://user-images.githubusercontent.com/24811163/32060092-bca6e580-ba65-11e7-9d79-445394b74b79.png)

**Comment by bobintetley** [comment]
You don't have a matching account linked to your payment type under Financial->Accounts. It's only a warning and does not stop the payment being created, it's just that you have the option turned on to create matching transactions from payments and without an income account linked to your payment type, the system can't do it.
