### ISSUE TITLE
Found animals web service

### ISSUE THREAD

**Issue by inghamn** [bobintetley/asm3#329]
It would be nice to have a web service for "Found Animals".  We are wanting to publish these on our Drupal site.

**Comment by inghamn** [comment]
I've already written a Drupal 8 module for integration with ASM.  I'll be adding this feature to it, once I've got the service.

Have you tried out our module?
https://github.com/City-of-Bloomington/drupal-module-asm

**Comment by bobconn66** [comment]
Rockin'!  Thanks!  Have not tried it out.

**Comment by bobconn66** [comment]
Do you know of anyone else who works in Drupal 8 with ASM?

**Comment by inghamn** [comment]
No one ever responded on the Forums about it.  So, no one that I know of. 
@bobintetley might know better than I.

**Comment by bobintetley** [comment]
I guess it would be straightforward to have service calls that returned the active lost and found animals set. Would that work for you? 

You can also use the html_report call to get pretty much any data from the system and output it in any text format you want (it doesn't strictly speaking have to be HTML - the report engine assembles blocks of text).

**Comment by inghamn** [comment]
Yes, the active lost and found animals is what I'm looking at.  I'll try to write up an implementation today.  I'm expecting it will just be adding another function to service.py

**Comment by inghamn** [comment]
My first pass didn't include all the information we wanted here in Bloomington.  For our website, we're hoping to have "Found Animals" published in a similar way to "Adoptable Animals".   The adoptable animals include a WEBSITEIMAGECOUNT, which the found animals do not.

https://bloomington.in.gov/animal-shelter/animals

The found animals do have medi attached to them, but no way to mark each media file as a WEBSITEIMAGE.  It looks like the media attached to the found animals are available to the outside world at `/image?mode=media&id=ID`.

So, I could add a MEDIACOUNT field to lostfound.get_foundanimalquery and expect JSON clients to know how to craft the URL which would go inside an <img src="">

**Comment by bobintetley** [comment]
Also added WebsiteMediaID and other WebsiteMedia fields similar to animal so that a URL can be built.

**Comment by inghamn** [comment]
This is wonderful. Thanks for adding to the services.  I hope to try it out in our Drupal module soon.
