### ISSUE TITLE
Detailed Inventory at Date pulls animals latest location within shelter, not location at that date

### ISSUE THREAD

**Issue by cohense** [bobintetley/asm3#347]
When running the Detailed Shelter Inventory at Date, our animals are not pulling from the correct location when looking at an inventory prior to that day. Rather, that animal's latest location within the shelter (prior to adoption) is shown. That is, an animal entering the shelter on 11/12, moved from "Stray" to "Adoptables" on 11/18, and adopted on 11/21, will be located under "Adoptables" from 11/12 to 11/21.

**Comment by bobintetley** [comment]
Sorry, that info isn't available as location history is not stored. 

The report helpfully shows the location as it may still be the correct location, or the one the animal left from if it is no longer on shelter, but there's no way for a historic inventory to show the location the animal was actually at on that date as it isn't known.
