### ISSUE TITLE
Error of SQL go to 100% of our CPU.

### ISSUE THREAD

**Issue by XxCoolGamesxX** [bobintetley/asm3#348]
Hey Robin,

We have error with your ams3 program and we have more at 1000 dogs and cats on ams3 program.

Here error we have of it. Eat all of our CPU power.
![nvidia share_2018-01-31_11-50-55](https://user-images.githubusercontent.com/1343385/35620710-4258e6d4-0682-11e8-8023-a617353b73b2.jpg)

Here commands it do on MySQL: https://www.dropbox.com/s/m81rcig02gzw2pj/Error%20SQL.txt

If you one the MySQL data send me email to info@protectoraanimalesalicante.org and go to send you data of MySQL.

Kind regards,
Charles

**Comment by bobintetley** [comment]
That looks like the timeline query. Are you running on the 39 build or are you tracking the HEAD here in github?

Does the query ever complete?

I'm hoping you're still on 39 as there were at least 10 new indexes added in 40 - that and release 40 is also now finally  complete and being uploaded in the next 24 hours.

**Comment by XxCoolGamesxX** [comment]
Dear Robin,

First thanks for your quick answer!

Currently we are running 40 build of Sat  2 Sep 09:07:14 BST 2017 
The reason to use that version was our need of the automatic publishing functionality on our web site.

The problem we are facing now is intermittent, do you think that your new release can fix it?

Kind Regards,
Charles

**Comment by bobintetley** [comment]
It's possible - September was 5 months ago. I'd worry about the issue being intermittent rather than consistent though, that could point at some kind of environmental issue. The release should be going out later today (or you're welcome to sync from the trunk as there shouldn't be any more changes).

**Comment by XxCoolGamesxX** [comment]
Hey Robin, in my last comment i said the problem was intermittent but after further testing the CPU is at 100% all the time not just every so often. Also i have found out that the problem is "animalmedical" and "animalmedicaltreatment" also the dates 31, 30 and 29 are causing the loop, if i remove these dates the error disappears. I would like to know why these dates are causing issues.

Here is the one that is causing issues with the dates: https://www.dropbox.com/s/zznx3ssscbvzuga/animalmedical-and-animalmedicaltreatment-error.sql

This one is where the three dates have been removed and i have no errors: https://www.dropbox.com/s/ex0kqq6cz7z9kz9/animalmedical-and-animalmedicaltreatment-fix.sql

I put the latest update of the program of GitHub but i am still having the same error.

Kind Regards,
Charles

**Comment by bobintetley** [comment]
Hi, I'd love to know why those dates are causing an issue with MySQL too? When you say 31, 30 and 29 - is that the day of a particular month? What do you mean? Did you get around the bug by deleting rows that contained those dates or by changing the dates?

I can't think of a reason they would cause problems. I would try REPAIR on both those tables first, and then re-indexing them via dump/restore to see if you have any kind of corruption or hard disk issue causing the problem. 

https://dev.mysql.com/doc/mysql-installation-excerpt/5.5/en/rebuilding-tables.html 

The timeline query that you pointed at in particular uses the index on animalmedicaltreatment_DateRequired and if removing columns with certain dates is the fix, that might explain why it helps and it's this index causing issues.

**Comment by XxCoolGamesxX** [comment]
The three dates are from January and i got around the bug by deleting the rows. I can't do the repair because on Debian 9 the default MySQL is Mariadb 10.1.26, what do i need to do in MySQL to make it work with your program or how to fix the database. I don't think there is a problem with my hard disk because i am using VPS OVH -SSD.

**Comment by bobintetley** [comment]
We also use OVH SSD for some hosts, but we use PostgreSQL 9.6 on Debian 9. It doesn't look like you even have a lot of data in those two tables, so it's not a problem of data size. I have no idea why storing those dates would cause MySQL to hang.

REPAIR works with MyISAM so I guess you're using the InnoDB storage engine with MariaDB 10.1.26 like I am on my development machine here. 

If you use the link I added above, it describes how to rebuild a table and its indexes by dumping it and then restoring it. 

With the dataset being so small, you could try dropping that date index on animalmedicaltreatment to see if it does anything - 

DROP INDEX animalmedicaltreatment_DateRequired

put it back with 

CREATE INDEX animalmedicaltreatment_DateRequired ON animalmedicaltreatment (DateRequired);

**Comment by XxCoolGamesxX** [comment]
I tried to put the first command in phpmyadmin but i get this error: 
![firefox_2018-02-01_16-59-32_preview](https://user-images.githubusercontent.com/1343385/35688504-9adc24ac-0771-11e8-8051-a82dd7394b0c.png)

**Comment by bobintetley** [comment]
Sorry. Stupid MySQL makes you specify the table as well:

DROP INDEX animalmedicaltreatment_DateRequired ON animalmedicaltreatment

Try using ASM without the index to see if it makes any difference to the timeline result. It's the only thing I can think of and even then it's seriously clutching at straws.

**Comment by XxCoolGamesxX** [comment]
I did the commands of "mysqldump asm-test > dump.sql" and "mysql asm-test < dump.sql" did not fix error.

and

![image](https://user-images.githubusercontent.com/1343385/35689201-39700aec-0773-11e8-9dde-a6dc09b66107.png)

**Comment by bobintetley** [comment]
That is really odd, it's definitely there. What happens if you try to create that index manually? (the CREATE INDEX statement above) 

I've no idea why the index wouldn't be there as it's been part of the database schema since ASM 2. This whole thing is crazy and makes no sense at all!

**Comment by XxCoolGamesxX** [comment]
I explain in a video: https://www.dropbox.com/s/w9j6xp5i42ccs1r/MySQL-O.o.mp4

**Comment by XxCoolGamesxX** [comment]
Oh ok. I add back the:
```
ALTER TABLE `animalmedicaltreatment`
  ADD PRIMARY KEY (`ID`),
  ADD KEY `animalmedicaltreatment_AnimalID` (`AnimalID`),
  ADD KEY `animalmedicaltreatment_AnimalMedicalID` (`AnimalMedicalID`),
  ADD KEY `animalmedicaltreatment_AdministeringVetID` (`AdministeringVetID`),
  ADD KEY `animalmedicaltreatment_DateRequired` (`DateRequired`);
```
Fix error of loop.

**Comment by XxCoolGamesxX** [comment]
Thank for your time to help me on is problem. Now i go to add again index to all table.

**Comment by bobintetley** [comment]
I'm glad you got it fixed!
