### ISSUE TITLE
MySQL problems with v_owner

### ISSUE THREAD

**Issue by inghamn** [bobintetley/asm3#354]
The v_owner view was already slow in 39, taking about 10 minutes to return one row.  In v40, the addition of another dependent subquery field increased the query time geometrically.

This query takes over an hour now.
```sql
select * from v_owner where ID=1 limit 1;
```

**Comment by bobintetley** [comment]
How bizarre - a big part of the issue with 39 was the use of SELECT DISTINCT in the view, which we got rid of in 40. The new subquery is not causing us any issue on PostgreSQL even with very large databases. I guess it's the "Surrender" subquery? One thing I'd check is to make sure you have indexes on animal.BroughtInByOwnerID and animal.OriginalOwnerID as that could explain the slowdown.

**Comment by bobintetley** [comment]
I think the media join might be new as well - you should have indexes on media.LinkID, media.LinkTypeID and media.WebsitePhoto

**Comment by inghamn** [comment]
The queries are happening during the database upgrade scripts going from 39 to 40.  I dropped all our custom reports and the query still happens during the upgrade process.

**Comment by inghamn** [comment]
v_animal also runs slow.  It gets called during the upgrade and takes 10 minutes to return the one row.

```sql
SELECT * FROM v_animal WHERE ID = (SELECT MIN(ID) FROM animal) LIMIT 1;
```

**Comment by bobintetley** [comment]
Ok, I've found it. It's happening as part of schemajs in code.py (line 4643).

That target is hit once for every logged in user to populate code complete in the SQL editor. You could comment out the for loop that runs for dbupdate.VIEWS to get things going again.

**Comment by bobintetley** [comment]
it's hugely inefficient as well, I'm going to add a fix so it only looks this stuff up once and caches it, but I'd be curious to find out why the views are so slow for you. If you run the slow query manually with EXPLAIN does it give anything useful?

**Comment by inghamn** [comment]
Yes, its the fields that are derived with case() statements against subqueries.  

```sql
(case when exists(select oi.ID from ownerinvestigation oi where (oi.OwnerID = o.ID)) then 1 else 0 end) AS Investigation,
(case when exists(select ac.ID from animalcontrol ac where ((ac.OwnerID = o.ID) or (ac.Owner2ID = o.ID) or (ac.Owner3ID = o.ID))) then 1 else 0 end) AS Incident,
(case when exists(select bib.ID from animal bib where ((bib.BroughtInByOwnerID = o.ID) or (bib.OriginalOwnerID = o.ID))) then 1 else 0 end) AS Surrender
```

MySQL cannot use indexes on these derived tables.  I realize it's probably not a problem in PostGres, but if we rewrote the subqueries as left joins it would work fast in both.

**Comment by bobintetley** [comment]
It can't? Wow, how crap is MySQL? :D

**Comment by inghamn** [comment]
Subquery performance has been a long standing thing with MySQL.  Usually, it's not a problem.  All of these subqueries can be rewritten using left joins, which is typically what MySQL people will do.

For what it's worth, rewriting them as joins would probably improve performance in Postgres as well.

**Comment by inghamn** [comment]
Is there a place in the code where the views are defined, where I can update the SQL definition? Or are the definitions themselves generated dynamically?

**Comment by inghamn** [comment]
By switching the case() select for Owner Investigations, I was able to get MySQL to use indexes for the other two case selects.  I replaced the Investigation field with a more simple select count(*).

Instead of 
```sql
(case when exists(select oi.ID from ownerinvestigation oi where (oi.OwnerID = o.ID)) then 1 else 0 end) AS Investigation
```

I used
```sql
(select count(*) from ownerinvestigation where OwnerID=o.id) as Investigation
```

Would it be too damaging to the view to return a count instead of just zero or one?

**Comment by inghamn** [comment]
```sql
select  o.ID AS ID,
        o.OwnerType AS OwnerType,

        -- All the other Owner fields left out for
        -- demonstration purposes

        o.ID AS PersonID,
        ho.OwnerName AS HomeCheckedByName,
        ho.HomeTelephone AS HomeCheckedByHomeTelephone,
        ho.MobileTelephone AS HomeCheckedByMobileTelephone,
        ho.EmailAddress AS HomeCheckedByEmail,j.JurisdictionName AS JurisdictionName,
        web.ID AS WebsiteMediaID,
        web.MediaName AS WebsiteMediaName,
        web.Date AS WebsiteMediaDate,
        web.MediaNotes AS WebsiteMediaNotes,
        (select count(*) from ownerinvestigation where OwnerID=o.id) as Investigation,
        (case when exists(select ac.ID from animalcontrol ac where ((ac.OwnerID = o.ID) or (ac.Owner2ID = o.ID) or (ac.Owner3ID = o.ID))) then 1 else 0 end) AS Incident,
        (case when exists(select bib.ID from animal bib where ((bib.BroughtInByOwnerID = o.ID) or (bib.OriginalOwnerID = o.ID))) then 1 else 0 end) AS Surrender
from      owner        o
left join owner       ho on ho.ID = o.HomeCheckedBy
left join media      web on (web.LinkID = o.ID and web.LinkTypeID = 3 and web.WebsitePhoto = 1)
left join jurisdiction j on j.ID = o.JurisdictionID```

**Comment by inghamn** [comment]
To make it go even faster we could replace all three case statements with basic counts.
```sql
select  o.ID AS ID,
        o.OwnerType AS OwnerType,

        -- All the other Owner fields left out for
        -- demonstration purposes

        ho.OwnerName       AS HomeCheckedByName,
        ho.HomeTelephone   AS HomeCheckedByHomeTelephone,
        ho.MobileTelephone AS HomeCheckedByMobileTelephone,
        ho.EmailAddress    AS HomeCheckedByEmail,
        j.JurisdictionName AS JurisdictionName,
        web.ID             AS WebsiteMediaID,
        web.MediaName      AS WebsiteMediaName,
        web.Date           AS WebsiteMediaDate,
        web.MediaNotes     AS WebsiteMediaNotes,
        (select count(*) from ownerinvestigation where OwnerID=o.id) as Investigation,
        (select count(*) from animalcontrol where (OwnerID=o.id or Owner2ID=o.id or Owner3ID=o.id)) as Incident,
        (select count(*) from animal where BroughtInByOwnerID=o.ID or OriginalOwnerID=o.ID) as Surrender
from      owner        o
left join owner       ho on ho.ID = o.HomeCheckedBy
left join media      web on (web.LinkID = o.ID and web.LinkTypeID = 3 and web.WebsitePhoto = 1)
left join jurisdiction j on j.ID = o.JurisdictionID
```

**Comment by bobintetley** [comment]
This all seems vaguely familiar and COUNT was how it was originally - didn't we move to the CASE/EXISTS because of performance problems with COUNT on MySQL last year? 

I'm fine with switching to COUNT as it makes a lot more sense than CASE/EXISTS.

**Comment by bobintetley** [comment]
the views are generated dynamically from get_X_query. If you change person.get_person_query, then delete the configuration entry itemname LIKE 'DBView%' that will cause ASM to regenerate the views next time you hit the home screen.

**Comment by bobintetley** [comment]
I'm going to commit the COUNT change now since it's fine for us, so you might want to wait two minutes and pull from git.

**Comment by bobintetley** [comment]
I've also had schemajs derive the field names of views instead of attempting to run them so no more MySQL problems. 

Reading up on it, it seems that MySQL views are a complete hack and their engine implements them by running the view query to create a temporary table *with none of the indexes*. No wonder it's so bad!

**Comment by inghamn** [comment]
The solution from a year ago would have returned multiple rows for the same owner when they had more than one incident.  I think that's why there was a DISTINCT added to the person_query.  That old DISTINCT coupled with the counting certainly caused performance problems.

The solution back then was to do a lot more JOINS and rely on GROUP BY or DISTINCT to squash it down to a single row per owner.  This was done to remove the subqueries that were written into the fields of the select statement.

Somewhere along the way, the subquery fields returned, I'm guessing because of not wanting to do DISTINCT or GROUP BY anymore.

I suspect the real performance hit comes when combining CASE() on the result of a subquery done inside a field.  ie.
```sql
(case when exists(select oi.ID from ownerinvestigation oi where (oi.OwnerID = o.ID)) then 1 else 0 end) AS Investigation
```
In the current case the plain count(*) subquery is fine.  You could even add the CASE WHEN > 1 to convert non-zero counts back to just one (with no performance hit).  This is because count(*) only returns one row (the number).

The performance hit comes from selecting multiple rows in the subquery
```sql
(case when exists(select oi.ID from ownerinvestigation oi where (oi.OwnerID = o.ID)) then 1 else 0 end) AS Investigation
```
This is selecting a bunch of ID's for each row of the owner.  Now we have a derived table as a subquery, and MySQL cannot use indexes on the derived table.
