### ISSUE TITLE
Found animals service not populating Media fields

### ISSUE THREAD

**Issue by inghamn** [bobintetley/asm3#359]
For our json_found_animals response, the WebsiteMedia fields are not being populated when a found animals has media attached

**Comment by bobintetley** [comment]
It only returns the preferred media (media.websitephoto = 1) - does the found animal have a preferred icon? It only started assigning it by default to the first image after the update last week, so existing found records will need it manually adding on the media tab.

**Comment by inghamn** [comment]
The media tab showed the icon on the animal, however it was not being included in the json response.  However, editing the media again and redoing the "Default Image for this record and the web" made it show up in the json.  I guess we'll need to run through and manually update all the media for found animals.
