### ISSUE TITLE
Internal Server Error - Person Flag & Reports

### ISSUE THREAD

**Issue by glherriott** [bobintetley/asm3#360]
I appear to be receiving an internal server error when I try to add more than one 'person flag' on the lookup data. I can add and delete the first entry fine, but when creating a second flag I get an error.

I get the same error when I go to setting>reports>sheltermanagerhome to install a report.

Any ideas?

Many Thanks

**Comment by bobintetley** [comment]
Is this a sheltermanager account or a self hosted install? If it's a sheltermanager account, please email us at support@sheltermanager.com

If not, do you get any errors posted in the webserver log?

**Comment by bobintetley** [comment]
either way, this is environmental and not a program bug

**Comment by glherriott** [comment]
Hi,

It's self-hosted. You're right it's environmental, was just wondering if you had come across this before as it seems strange it's only on those two parts of the system. I'll take a look at the webserver log and see what I can find. Thanks for your help.

**Comment by bobintetley** [comment]
I've seen it on postgresql when the sequences are out of sync with the data. You can fix that by running this query:

DELETE FROM configuration WHERE ItemName LIKE 'DBView%'

Then visiting the home screen to have ASM regenerate the sequences.
