### ISSUE TITLE
Documents only load from "Animal" tab

### ISSUE THREAD

**Issue by inghamn** [bobintetley/asm3#376]
Documents fail to load except when chosen from the animal tab.  For instance, choosing the Payments tab, then trying to load generate a receipt.

The result is a new browser window at `/document_gen?linktype=DONATION&id=3126,&template=2`
displaying "None".

![payments](https://user-images.githubusercontent.com/630282/36442140-c0f4acc4-1642-11e8-98c0-706c66ce05b5.png)

**Comment by bobintetley** [comment]
I know this was fixed, but that whole area has been refactored to use a new documenttemplate table, so untangling what it was is difficult. I *think* it might be that the parameter name was changed and it shouldn't be passing template=X, but dtid=X or dbfsID=X in header_edit_header.js/template_list

I guess I need to keep an install of 40 on one side so I can backport fixes like this.

**Comment by inghamn** [comment]
I don't know if you need to backport, if you've already fixed this.  Semantic version numbers would help a little in being able to know what's been applied on some production machine.

We just went live in production today, I'm having to tag our own repository to keep track of what commit we've pushed to production.  We're running https://github.com/City-of-Bloomington/asm3/commit/256830e3f4bda7547b74ad7f230b743c473e1d2c from five days ago.

**Comment by bobintetley** [comment]
Ah good, I hoped that bug wasn't in 40! We're running the master branch in production for 12,000 users right now, so I really hope so :)

**Comment by inghamn** [comment]
I'll try out installing from the very latest commit in master.  I expect that will take care of it.
