### ISSUE TITLE
Hide homechecker slider

### ISSUE THREAD

**Issue by bobintetley** [bobintetley/asm3#379]
If a person doesn't have the homechecker flag, we should be hiding the homechecker slider. Same goes for the two fields membership expiry and membership number if they don't have the member flag (I think number is used for people with the vet flag too).

**Comment by julian-poidevin** [comment]
Hey @bobintetley, what about the two fields membership expiry and membership number you are talking about in the issue description, it seems your commit only concerns the homecheckers accordion.

**Comment by bobintetley** [comment]
It was already done as part of a different refactoring ticket #181 that I committed yesterday

**Comment by julian-poidevin** [comment]
Nice, thanks !
