### ISSUE TITLE
Static HTML Website Embed Stopped Working

### ISSUE THREAD

**Issue by Katrinamp** [bobintetley/asm3#382]
Hello, 
For the past couple of years we have had our adoptable dogs embedded using the HTML Website Embed option. The code we are using to do so is accurate to the manual: <iframe src="https://public.sheltermanager.com/animals/hh0367" width="100%" height="600px" /> 

However today that started rendering the following error message:
Forbidden
You don't have permission to access /animals/hh0367/ on this server.
Apache/2.4.25 (Debian) Server at public.sheltermanager.com Port 443

For now, I've rectified the situation by adding in the API version  so that the dogs are showing (that works fine) but we prefer the embed option because it looks cleaner. You can view the error message on this page: https://www.helpinghoundsdogrescue.org/adopt/ (scroll down past the API version and you'll see the error message for the html embed near the bottom.)

Thanks,
Katrina

**Comment by ltblrescue** [comment]
We are having the same issue at www.ltblrescue.org/adoptables.html

**Comment by bobintetley** [comment]
Re-run the HTML publisher from within ASM to regenerate your site. The adoptable animal webserver has been upgraded and moved to the US to be closer to customers, we attempted to move live data but there was a lot of stale data on the server and some has been missed. The overnight batch will run shortly and put them back as well.

**Comment by Katrinamp** [comment]
Robin, This is still not working for us.

**Comment by Katrinamp** [comment]
Update: This is now working. Thanks.
