### ISSUE TITLE
Wordkey tokens cannot access first of type

### ISSUE THREAD

**Issue by ppaschka** [bobintetley/asm3#383]
It would make health records clearer if you could use Wordkeys to group vaccinations. For example:
FVRCP: <\<VaccinationGivenFVRCP1\>>, <\<VaccinationGivenFVRCP2\>>

It would also be nice if you could do the same thing with medications, for example to include both deworming dates.
Pyrantel: <\<MedicalTreatmentGivenPyrantel1\>>, <\<MedicalTreatmentGivenPyrantel2\>>

**Comment by bobintetley** [comment]
What is the use case for this? In most cases I can think of you're interested in the first and the last.

**Comment by ppaschka** [comment]
Omitting Recent still gives the most recent vaccination. I tried <\<VaccinationGivenFVRCP\>> and <\<VaccinationGivenRecentFVRCP\>> and got the same date for both, despite having 2 FVRCP vaccinations on file.

**Comment by bobintetley** [comment]
it looks like a bug in update_tags - it only makes one pass and uses descending

**Comment by ppaschka** [comment]
It would be a huge help. We have a few long-term residents that have more than 2 vaccinations, but that's infrequent enough that we could add those manually. 

For the medications, it works to use StartDate, NumberOfTreatments, and LastTreatmentGiven. It would be nice to have dates for some regimens, such as deworming, which have several spread out treatments. They don't always happen right on schedule, so the extra detail would be useful. But it's not necessary and if it's a hassle to implement, I wouldn't worry about it. Thanks for your help!
