### ISSUE TITLE
Anisble not configuring https urls in sitedefs

### ISSUE THREAD

**Issue by inghamn** [bobintetley/asm3#398]
When setting up a site that is SSL only, Ansible needs to edit all the URLs contained in sitedefs.py and change them to the https:// versions.

I have not tested to see if each of the servers listed actually support SSL, but Ansible needs to at least do the settings correctly.

**Comment by inghamn** [comment]
Is there a reason for these to ever be plain HTTP links?  Should all of the URLs defined in sitedefs.py be https:// all the time?
* URL_NEWS
* URL_REPORTS
* MAP_LINK
* OSM_TILE_MAPS
* BULK_GEO_NOMINATIM_URL
* BULK_GEO_GOOGLE_URL
* VETENVOY_US_BASE_URL

**Comment by bobintetley** [comment]
Last time I checked Nominatim and OSM did not offer SSL, the others are probably all fine as SSL.

**Comment by inghamn** [comment]
It looks like OSM and Nominatim are now on SSL.
https://www.openstreetmap.org/#map=9/38.9957/-86.7755
https://nominatim.openstreetmap.com/

I've updated the sitedefs that ansible installs.
I'm wondering if it would be good to update the real /srv/sitedefs.py

**Comment by bobintetley** [comment]
yep, will update. Thanks for checking back on that!

**Comment by bobintetley** [comment]
Sorry, hit the wrong button. Also, OSM are still not offering an SSL version of the map tiles server. I used to proxy them through an SSL server but there's not much point.

**Comment by inghamn** [comment]
I think the OSM tile server is now
https://{s}.tile.openstreetmap.org

http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png

**Comment by bobintetley** [comment]
yep, that seems to work. Cheers Cliff :)
