### ISSUE TITLE
Available Dogs Page not Loading

### ISSUE THREAD

**Issue by Katrinamp** [bobintetley/asm3#400]
Hello, 
Our Available Dogs html page is not loading. It can be found here: https://public.sheltermanager.com/animals/hh0367

I tried republishing but no luck; still coming up blank. 

Thanks
Katrina

**Comment by bobintetley** [comment]
It seems to be loading fine? Please don't raise development bugs for environmental issues - if you're using sheltermanager.com, please email us for support at support@sheltermanager.com
