### ISSUE TITLE
Missing media functionality in service API

### ISSUE THREAD

**Issue by jgardynik** [bobintetley/asm3#424]
I noticed that you added the ability to use additional media in the publisher via this commit:

31/05/17 Add WEBSITEMEDIANAME2-4 shorthand for publish.get_animal_view

But this information is not available in the Service API. Neither is there a way to get additional images via the animal_image API call.

My suggestion would be to add fields into the json_* and xml_* calls for additional media info, and add another parameter to the animal_image call to get secondary images, such as imageNum=x, where x defaults to 1 (the primary image) if not included to preserve current functionality.

**Comment by bobintetley** [comment]
You can get additional images from the animal_image call - pass the seq parameter. seq=1 is the preferred, 2+ are the extra ones. The property "WebsiteImageCount" in the json/xml calls tells you how many images an animal record has.

**Comment by jgardynik** [comment]
Oh, nice. Looks like the docs just need to be updated, then. Thanks!

**Comment by bobintetley** [comment]
Weird - maybe it's something we only put in the documents recently. https://sheltermanager.com/repo/asm3_help/service.html#animal-image

**Comment by jgardynik** [comment]
I'm on version 40 right now, self-hosted, so that might be it. I'm a little leery of running directly from the github code, as a bug could be introduced that stops our facility until it's fixed.

I do hope that your next release tag isn't another year out, though. 😄

**Comment by jgardynik** [comment]
Oh, nevermind. Apparently it was caching version 39's page, despite me doing a force refresh (I just updated this weekend). Carry on!

**Comment by bobintetley** [comment]
me too, the plan is for late July :)
