### ISSUE TITLE
Hi!  I'm helping a new organization adopt Shelter Manager.  If I forget to add the adoption fee during the create animal process, I can't find it anywhere to update it later.

### ISSUE THREAD

**Issue by Fosterkit50** [bobintetley/asm3#430]
Hi!  I'm helping a new organization adopt Shelter Manager.  If I forget to add the adoption fee during the create animal process, I can't find it anywhere to update it later.  The manual shows it on the animal details screen, but it's not there on the version I'm using.

**Comment by bobintetley** [comment]
Have they hidden it with the option under Settings->Options->Remove ?

github issues are for development issues, please use the forum or email us for support.
