### ISSUE TITLE
Payment processor integration

### ISSUE THREAD

**Issue by bobintetley** [bobintetley/asm3#463]
While looking at the stuff for VPS (value payment systems in the US), it seems we could integrate payment providers into ASM. A simple superclass would provide methods for making a request to a payment provider for an amount/item, and receiving notification from the provider that payment was successful.

PayPal would be an obvious place to start. Making a request is a form post and receiving payment info is done via IPN, the return URL is stamped as part of the request. We already have a lot of this code in sheltermanager's own billing systems so PayPal would be quick and easy to do.

A button on the payment tab/book would allow requesting payment from someone via email if their payment is due but not received. An email would be sent to the person linked to the due payment. The email would contain a link to the service API with the ownerdonation.ID value referencing the payment. The service API would have a requestpayment method (paymentprovider?) that then uses the class to get them to the payment provider's checkout with the info filled out. 

The notification URL is another call in the service API for notifypayment or something. How to detect which payment provider is calling it can be done by either calling each one to figure it out, or passing an extra parameter to the notify url so it knows (I think PayPal allow this).

**Comment by bobintetley** [comment]
Stripe is even better as their process is synchronous. It could be handled with a single service call that passes in the ID of the due payment to be paid. One of the parameters you pass is the payment processor you want to use (default stripe and only stripe supported to start with).

**Comment by bobintetley** [comment]
With the new SCA in the EU, Stripe now has to be asynchronous - I imagine the US will follow with some equivalent. In this case, it means the model is now more similar to PayPal (redirect to their checkout, asynchronous callback for receipt).

**Comment by bobintetley** [comment]
Payment processor config is needed for which one is active and appropriate credentials.

**Comment by bobintetley** [comment]
This needs to support one or more payment IDs that are added together. This is so donations can be requested with fees, but also allows users to request multiple payments in one go from a customer.

**Comment by julian-poidevin** [comment]
Wow, amazing work !

**Comment by bobintetley** [comment]
Thanks! There's a lot more to do! That's only the provider for PayPal done (I will at least add Stripe before I'm finished this week) and there's testing and documentation to do. It should hopefully be a very useful feature.
