### ISSUE TITLE
Provide ability for regular users to reset their own passwords

### ISSUE THREAD

**Issue by jfburke3** [bobintetley/asm3#534]
**Is your feature request related to a problem? Please describe.**
It will stop users from bugging me to reset their passwords for them.

**Describe the solution you'd like**
I would like the ability for users to be able to reset their own passwords.  For example, they could be e-mailed a link to click on to begin that process.  (Not unlike the e-mail them credentials described in #362 )

**Describe alternatives you've considered**
I'm not aware of any alternatives.

**Comment by bobintetley** [comment]
Users can change their passwords by clicking on the user menu at the top right folllowed by "Change Password". Is the issue that your users are constantly forgetting their passwords?

**Comment by jfburke3** [comment]
Yes, forgetting.  They seem to usually let the browser save them, but then when they delete the cache, cookies, etc., seem to also forget to not delete saved passwords.

**Comment by bobintetley** [comment]
See #758
