### ISSUE TITLE
Cage cards always say "Dogs do not display true personality in kennels" no matter what species the card is for

### ISSUE THREAD

**Issue by jfburke3** [bobintetley/asm3#535]
**Describe the bug**
Cage cards always say "DOGS do not display true personality in kennels, even when it isn't for a dog.

**To Reproduce**
1. Add an animal of species Rabbit.
2. Click on Report
3. Scroll down to any of the cage card reports.
4. Search for the rabbit's name, click it, click Generate.
5. See the line "Dogs do not display true personality in kennels" near the top of the rabbit's cage card.

**Expected behavior**
Cage cards should reflect the species they're printed for.

**Comment by bobintetley** [comment]
Edit the report and edit the text to something you'd prefer. Settings->Reports. This is not a bug.
