### ISSUE TITLE
Ampersand doesn't work in passwords; no list of acceptable special characters

### ISSUE THREAD

**Issue by jfburke3** [bobintetley/asm3#536]
**Describe the bug**
If you include an ampersand (&) in your password, you can't log in.

**To Reproduce**
1. Set your password to something that includes an ampersand in it.
2. Try to log in using your new password.
3. Beat your head on the desk in frustration as you keep resetting your password to something with an ampersand and still can't log in.
4. Clean blood from desk.

**Expected behavior**
I expect to be able to log in, or at least for the set-password to tell me what special characters are allowed.

**Additional context**
An alternative to allowing ampersands in passwords would be to provide a list of what special characters are allowed.

**Comment by bobintetley** [comment]
Are you using the mobile app ? There is a login bug in the app where URL encoding is not being handled correctly, so using ampersand, hash or equals in a password will break login. I can't reproduce this logging in normally via browser.

**Comment by jfburke3** [comment]
Yes to the mobile app.  I can't remember if I tried using a regular browser.  Will see if I can test that after the Christmas panic.

**Comment by bobintetley** [comment]
fixed ready for updating in app stores
