### ISSUE TITLE
Ansible: need separate api_keys for map and geo provider

### ISSUE THREAD

**Issue by inghamn** [bobintetley/asm3#579]
When using Google for both maps and geocoding, you probably need to set up separate api_keys.  The ansible script uses the same api_key for both maps and geocoding.  We need to add support for separate api_key variables for maps and geocoding.

## Background:
Google maps now requires an api_key; plus, for security reasons, you should probably set "Application restrictions" on the api_key you create. This is to prevent people from impersonating you by reusing your api_key.  This is needed, since the api_key is published in plain text, as part of the url, in the source of the HTML to render the map.  It is highly recommended to set an HTTP Referrrer restriction on the use of your api_key for Google Maps.

Geocoding is done server to server, though.  And it turns out that Google does not support HTTP Referrer restrictions on the geocoding apis.  So, if you attempt to use the same (referrer restricted) api_key you've set for maps, Google will send back a 403 error, saying that restriction is not permitted.

To prevent other people from stealing your key and impersonating you, you should create an additional api_key with "Application restrictions: IP addresses".  This will be the api_key you should configure for the geocoding.

**Comment by bobintetley** [comment]
Geocoding used to be done in the JS at the frontend, but I switched it to use the backend a while ago. You're right that it could be two separate API keys for security reasons. I'll split it.

**Comment by bobintetley** [comment]
They are separate keys already - geo_provider_key is the one for geocoding at the backend and map_provider_key is the one for rendering maps.

**Comment by inghamn** [comment]
You are correct, asm's python code correctly has separate configuration for both.  This is an issue with the ansible deployment script I've written, though.  I did not create separate ansible variables for them in my deployment.

**Comment by bobintetley** [comment]
Apologies, I didn't realise this was related to the ansible scripts. Carry on :)

**Comment by inghamn** [comment]
Would it be better if I split the Ansible deployment out into a separate Github repo?  Or, is it best to keep this all in one place?  Ultimately, I defer to you on how you would like to organize all this.

**Comment by bobintetley** [comment]
It would make more sense to keep it in one place since we're bundling the scripts with releases. I'd apply the appropriate milestone you intend to make fixes in and use issues the same way we do for everything else in a release.
