### ISSUE TITLE
Multiple Movements added with same Movement number

### ISSUE THREAD

**Issue by mudislandkid** [bobintetley/asm3#582]
I have been informed by users that multiple movements of the same type are being added instead of just one. They all have the same movement number. This is causing a lot of unecessary clutter as well as duplicating the animal in shelter view. As to how this is happening I have no idea. I have tried adding a movement on a test animal and it works just fine.

I have included some photos below to show you what I mean.

I have tried triggering batch processes manually, restarting the server and still no difference.

Many thanks for your help/advice in advance.

![image](https://user-images.githubusercontent.com/36311595/54671291-89233000-4aed-11e9-85a8-ef2f931dbfd9.png)

![image](https://user-images.githubusercontent.com/36311595/54671323-99d3a600-4aed-11e9-8813-7ceb6a5fd5e7.png)

**Comment by bobintetley** [comment]
This is not a bug, it's bad data. If you visit Archie's record and go to the media tab, you will have multiple preferred images causing the issue. Just visiting that tab will fix it as the system will spot it and correct it.

In future, please contact the support email address for help.

**Comment by bobintetley** [comment]
just to add, this is usually caused by an import or running queries directly.
