### ISSUE TITLE
Upload to Petfinder/Adoptapet only includes pic of 1 rabbit of a bonded pair

### ISSUE THREAD

**Issue by jfburke3** [bobintetley/asm3#585]
**Describe the bug**
Our rabbit rescue has several bonded pairs.  We log them in Sheltermanager separately, as they are individuals and it is necessary to track physical characteristics, health, medical treatment, etc., separately for each one.  However, when the software uploads to Petfinder/Adoptapet, it only includes a single picture, of one rabbit in the pair.  However, on the sites, they are correctly listed together (although the "bonded" box isn't marked for any of them).

**To Reproduce**
1. Create entries for 2 rabbits in Sheltermanager.  On the entry page, indicate that they are bonded.  On the media page for each one, upload at least one picture of each bun.
2. Upload to Petfinder & Adoptapet.
3. *time passes*
4. After the sites process the upload, inspect the online record for the pair.  Notice that only one of the photos added to the two buns is present.

**Expected behavior**
If we have separate pics of each rabbit as the preferred web photo for each one, we would expect both pictures to be added to their online profile.

**Comment by bobintetley** [comment]
Sorry, this is not a bug and is the expected behaviour. For bonded animals you should give both animals all of the pictures you'd like to see uploaded.
