### ISSUE TITLE
Allow additional fields to be inactive

### ISSUE THREAD

**Issue by bobintetley** [bobintetley/asm3#598]
Some users would like to retain the data in additional fields in case they want to bring them back later. Offer the ability to disable additional fields so they are no longer displayed, but can be resurrected.

I think we clear all attached additional fields for an animal during save, so this may be difficult.

**Comment by julian-poidevin** [comment]
@bobintetley In the same idea (didn't want to create an issue about that) :
We use "Additional Fields" to save information from Online Forms. For exemple, for a foster :
- If he has a garden
- If he has young children
- How many animals he can foster
- etc...

These additional fields are visible regardless of the person type.

**It would be great to be able to configure the additional fields visibility based on the person flags.**

**Comment by bobintetley** [comment]
A simpler approach is to name the flag "Hidden" so that the fields are still present and work, but they can be hidden from view.
