### ISSUE TITLE
Javascript error loading Medical Profile screen

### ISSUE THREAD

**Issue by inghamn** [bobintetley/asm3#599]
Cannot load the medical profile page.  A modal dialog shows up with a javascript error.

Go to Medical -> Medical Profile

```
ERROR: module_start [medicalprofile]: render: TypeError: v is null from format_comments@https://shelter-test.bloomington.in.gov/x.js?v=common_tableform.js&k=03040919:159:60
table_render/</<@https://shelter-test.bloomington.in.gov/x.js?v=common_tableform.js&k=03040919:253:32
each@https://shelter-test.bloomington.in.gov/static/lib/jquery/2.1.4/jquery.min.js:2:2880
table_render/<@https://shelter-test.bloomington.in.gov/x.js?v=common_tableform.js&k=03040919:227:17
each@https://shelter-test.bloomington.in.gov/static/lib/jquery/2.1.4/jquery.min.js:2:2880
table_render@https://shelter-test.bloomington.in.gov/x.js?v=common_tableform.js&k=03040919:223:13
render@https://shelter-test.bloomington.in.gov/x.js?v=medicalprofile.js&k=03040919:115:18
module_start@https://shelter-test.bloomington.in.gov/x.js?v=common.js&k=03040919:502:51
success@https://shelter-test.bloomington.in.gov/x.js?v=common.js&k=03040919:461:21
j@https://shelter-test.bloomington.in.gov/static/lib/jquery/2.1.4/jquery.min.js:2:26920
fireWith@https://shelter-test.bloomington.in.gov/static/lib/jquery/2.1.4/jquery.min.js:2:27738
x@https://shelter-test.bloomington.in.gov/static/lib/jquery/2.1.4/jquery.min.js:4:11251
b/<@https://shelter-test.bloomington.in.gov/static/lib/jquery/2.1.4/jquery.min.js:4:14765
```

![screen](https://user-images.githubusercontent.com/630282/57142097-ba984800-6d89-11e9-9291-673e1cbd4bb3.png)

**Comment by inghamn** [comment]
I upgraded to the latest commit in the master branch, and the error is still there.

In common_tableform.js, the table_render function is failing because the JSON contains rows without fields.

**Comment by inghamn** [comment]
After debugging some more, the JSON response has rows of data where the "COMMENTS" field is null.  This null value is passed to the format_comments() function as if it were a string.  Then it errors out when attempting to call v.replace.

**Comment by bobintetley** [comment]
Not sure how it's happened, but you've got NULL comments in your medical profiles. Just fix it in the database since the UI should always supply an empty string.

UPDATE medicalprofile SET Comments='' WHERE Comments IS NULL

**Comment by inghamn** [comment]
Should we update the javascript to be resiliant against passing null?
```js
format_comments: function(row, v) {
    if (v && typeof(v)=='string') {
        return config.bool("ShowFullCommentsInTables")
                ? v.replace(/\n/g, "<br />")
                : html.truncate(v, 80);
    }
    return '';
}
```

**Comment by bobintetley** [comment]
Not sure it's worth the bother if there's never any reason it should contain a null. If we did, then rather than type checking, I'd probably just wrap a common.nulltostr() around the expression to replace on.

**Comment by bobintetley** [comment]
mind you, this is a shared function - you're right, it should check inputs. I'll change.

**Comment by inghamn** [comment]
I can send a pull request with the type checking added to the format_* functions, if you like.

**Comment by inghamn** [comment]
Also, would it make sense to change the table definition for medicalprofile, so that the comments field is not null.  That way, the database makes sure this wouldn't happen?

**Comment by bobintetley** [comment]
it would, but we still have to import ASM2 databases from the old schema, which was a lot more lax in allowing nulls. That makes it hard for us to make any changes that would break that and it's safer to enforce those checks in the python code (smelly as that is). I forgot to reference this issue number and just committed a fix to format_comments

**Comment by inghamn** [comment]
Thanks for taking a look.  I've updated our medicalprofile table and we're no longer erroring.  We had many null values from 2017.

This null value problem could potentially resurface somewhere else in the system, with one of the other format_* functions.  I guess we'll wait and see.

**Comment by bobintetley** [comment]
I had a quick look and all of the endpoints called by the format_ functions do input checking for null, I think it was just that unchecked v.replace in format_comments. Hopefully we're good!
