### ISSUE TITLE
Reverse geolocation not working with google

### ISSUE THREAD

**Issue by inghamn** [bobintetley/asm3#601]
When you view a person in the system, who has an address, the lat/long comes out as 0,0.  The map then renders the location as off the coast of Africa.

I don't see any errors in the error log.  It's just that editing the address results in 0,0 for lat, long.

This may be a the same problem as #142 

I have confirmed our configuration.  We have defined geo_provider_key with out api-key frmo Google.  Also, in our Google Developers Console, we see traffic from this key, so at least some geo_coding in the system is making successful requests.

![screen](https://user-images.githubusercontent.com/630282/57234027-d9971400-6fed-11e9-8694-a8e08eb407a4.png)

**Comment by bobintetley** [comment]
Have you had a look in the debug log? geo.Google logs to /var/log/debug (and /var/log/messages if debug is enabled for it).

**Comment by inghamn** [comment]
Okay, thanks.  The debug logs exposed the problem.

Our gateway address changed over the last week. The new firewall address was not being permitted on Google's side.  I updated our Google Developers Console, and resolved the problem.
