### ISSUE TITLE
Deleting media mangles the entire media table's data

### ISSUE THREAD

**Issue by jgardynik** [bobintetley/asm3#608]
**Describe the bug**
Since updating to version 41 (which massively rewrote huge chunks of the system to use parameterised queries), I've found numerous problems having to do with type conversion screwing up queries. Most of them are minor, but the latest one I found is an absolute showstopper that has mangled my media table (with 70k records) to the point that I had to restore it.

Deleting the primary website/document photo from an entity causes it to flag literally every record in the media table as being the document/website photo for every single entity across the system. This causes it to overwrite any and all previous preferred images, and also causes it to completely break all view animal sections because it retrieves the same animal N times (where N is the number of media records that animal has).

**To Reproduce**
1. Add two images to an animal.
2. Delete the preferred image.
3. See error on shelter view where animals with multiple media now show up multiple times, and look in the database to see all records flagged with WebsitePhoto = 1 and DocPhoto = 1

**Expected behavior**
Properly typecast the ID you're retrieving so that it only affects the animal you're working on, found in media.py:562 and media.py:567, with int(ml.ID) . If they are not typecast, on my system at least they're not considered ints for the purposes of dbo.update(), which doesn't add the ID= part. This results in a query like this:

`UPDATE media SET WebsitePhoto=1 WHERE 75948;`

Which resolves to true and updates every record.

As a side note, I would also like to express concern that this preferred auto-setter is ignoring the ExcludeFromPublish flag and just choosing the earliest image from the system for that entity. This could be very bad. If I have two pictures, one of an animal's injury or surgery (properly set to not publish) and another, preferred picture of the animal that I need to delete for some reason, the last thing I want is that potentially graphic picture to be automatically set as the preferred doc/website photo and go out on our website before someone catches it. The queries to find other images should have "AND ExcludeFromPublish = 0" added to them. If there are no other valid images, then so be it (it'll default to no image, which is _far_ better than showing something it shouldn't).

**Version Info**
Debian Linux 9.6
Python 2.7.13
MariaDB 10.1.37
ASM 41

**Comment by bobintetley** [comment]
Thanks for tracking this down - I've seen a few open source DBs where this has happened and wondered how it got that way. This problem of ID fields not coming back from a query as int must be fault with the MySQLdb driver as it doesn't occur with PostgreSQL, where we do the majority of our testing.

I'll get a fix added for this and that's a great point about the excluded images, I'll fix that too.

**Comment by jgardynik** [comment]
I don't suppose I could push for a release in the near future instead of waiting for another 7 months based on your past two release dates. You have a lot of "Fix" entries in the current changelog that people who are using the open source version either have to piecemeal into the system or run directly off the master branch (which isn't a very good philosophy in a production environment, for exactly the reason that your commit to parameterize queries would have instantly broken many things).

I'm really wondering why there isn't better version control and maintenance on this project as a whole, though. Typically, fixes get backported to the current production version provided they don't create conflicts that were solved by new feature implementations. Many of your fixes are simple changes that should be a part of the current .deb package, because as it stands your current open source release is critically broken using the much more common MySQL engine.

And yes, I understand the answer of "if you don't like it, pay for hosted", but the reality is that doesn't work for us. We currently have a 33GB database and not the most reliable Internet. I can't have the shelter shut down if we lose access to the net because it's remotely hosted.

**Comment by bobintetley** [comment]
I'm working on getting an interim release out in the next week or so due to the severity of that bug. 

To be brutally honest, tighter version control and backported fixes to stable open source releases would take up more of our time and doesn't offer any benefit to the folks who pay our wages. I will try and push for us moving to smaller, more frequent releases to alleviate this a bit.
