### ISSUE TITLE
service method: html_flagged_animals

### ISSUE THREAD

**Issue by bobintetley** [bobintetley/asm3#610]
Quite often, foster groups want to show animals on their website that are in need of fostering. 

Since how an animal is considered in need of fostering would vary between groups and I don't think it's worth adding a built in flag, add an html_flagged_animals service call instead that can show any shelter animal with a particular flag.

A flag=X argument will be passed where X is a custom or built in flag that can be pattern matched against AdditionalFlags.

**Comment by Windy6** [comment]
Thank you!
