### ISSUE TITLE
After installing ASM3 in ubuntu Default password "letmein" is not working,how to login?

### ISSUE THREAD

**Issue by Varshap-Yiion** [bobintetley/asm3#636]

**Comment by XxCoolGamesxX** [comment]
Info is in the Doc: https://sheltermanager.com/repo/asm3_help/gettingstarted.html

**Comment by bobintetley** [comment]
This is not a bug or development issue. Please don't file support requests in github. Use the forum and give information from the syslog.

https://sheltermanager.com/site/en_forum.html
