### ISSUE TITLE
Improve french translation

### ISSUE THREAD

**Issue by julian-poidevin** [bobintetley/asm3#699]
I've installed ASM3 on a personal web server for my french association.
The application is not fully translated in french, I'm working to get it fully translated and will submit a PR when the work is completed. I'll refer to this issue in the upcoming PR.

Thanks a lot for the amazing work.

**Comment by bobintetley** [comment]
Thank you for contributing!

**Comment by julian-poidevin** [comment]
Hello,

Just for info, we have now (over 3397 words) :

- 1101 translated
- 1816 waiting for review
- 180 that needs a bit a work
- 299 untranslated

@bobintetley : before which date should we submit the pull request for this change to be integrated in ASM v43 ? 31th December ?

Thanks.

**Comment by bobintetley** [comment]
1 day before is good. Thanks for doing this!
