### ISSUE TITLE
Advanced search for flags does not work with flags which have accents

### ISSUE THREAD

**Issue by julian-poidevin** [bobintetley/asm3#715]
Hello,

I've added some additional flags in my ASM, some of these flags are containing special characters like accents (in french : é,è, à, ï .... etc). Here's it's "Abonné" which means "Subscriber" in french.

![image](https://user-images.githubusercontent.com/8756421/71889868-62e58400-3143-11ea-8f8c-4cf2ec36d648.png)

When I use advanced search to search for people with the "Abonné" flag: 
![image](https://user-images.githubusercontent.com/8756421/71890028-bd7ee000-3143-11ea-8424-b88c3465b75a.png)

The search is returning 0 results :
![image](https://user-images.githubusercontent.com/8756421/71890042-c53e8480-3143-11ea-8432-64fc9b69e868.png)

When I remove the "é" character, from "Abonné" to "Abonne" :
![image](https://user-images.githubusercontent.com/8756421/71890151-f5862300-3143-11ea-9644-77d1feddf0a6.png)

Then the search is working :
![image](https://user-images.githubusercontent.com/8756421/71890191-0c2c7a00-3144-11ea-9456-cbc6ce53dbf9.png)

**Comment by bobintetley** [comment]
There's a similar issue occurring when copying flags from an online form to a created person record (report from a Norwegian user).

**Comment by julian-poidevin** [comment]
Thanks ! I tested the changes on my ASM server, it's now working as intended.
