### ISSUE TITLE
asm3_adoptables_limit breaks with filters

### ISSUE THREAD

**Issue by bobintetley** [bobintetley/asm3#717]
When using the adoptable_js code, if you apply a filter to reduce the set, it breaks limits as limit is applied at the same time as filters, so you get fewer records than the limit.

It needs to be applied after the filter.

**Comment by bobintetley** [comment]
similar code area, the same user is requesting a sort token (like we use @ to specify numeric sorting) to specify random sorting.

**Comment by bobintetley** [comment]
Have chosen the SHUFFLE keyword instead, as shuffle is a better description than random sort.

**Comment by julian-poidevin** [comment]
Really nice for the SHUFFLE keyword, was looking for such a feature !
