### ISSUE TITLE
Leap year date is breaking animal records

### ISSUE THREAD

**Issue by jgardynik** [bobintetley/asm3#740]
Python is throwing a "day is out of range for month" exception trying to subtract 1 year from 2020-02-29.

/usr/lib/sheltermanager3/i18n.py in subtract_years
    if years == int(years): return date.replace( year = date.year - int(years)) 

date | datetime.datetime(2020, 2, 29, 0, 0)
-- | --
years | 1

**To Reproduce**
On our system, I can go to any animal. Or rather I can't, because it breaks.

**Expected behavior**
It should load the animal.

**Screenshots**
![Screenshot (38)](https://user-images.githubusercontent.com/12724261/75606808-d9509380-5aad-11ea-95eb-1f2c4627a9f2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 80

**Additional context**
Server is running version 42 on Linux.

**Comment by jgardynik** [comment]
I did fix this by commenting out that line and letting it fall through to the full timedelta function below. Not sure if that optimization is really necessary when it breaks on leap years.

**Comment by bobintetley** [comment]
See this patch: https://github.com/bobintetley/asm3/commit/36c6841bffee67dbbb48b2ab46297150d8a17f78

It's not totally necessary but can lead to the addition or subtraction of a day when adding a year.
