### ISSUE TITLE
Document button is not clickable anymore on voucher tab

### ISSUE THREAD

**Issue by julian-poidevin** [bobintetley/asm3#746]
When selecting a voucher in the voucher tab and trying to create a document from it, the button is not  clickable and the drop-down list of documents does not show up.

**Comment by bobintetley** [comment]
The document button was never there before, it's just been added along with wordprocessor support for vouchers. Do you get any errors in the js console?

**Comment by julian-poidevin** [comment]
Nope sorry, nothing shows up in the console.

**Comment by bobintetley** [comment]
Hmm. I can't recreate this in a local environment or production at sheltermanager.com so I think there's something environmental and odd going on. Have you got any document templates in your database when you go to Settings->Document Templates?

**Comment by julian-poidevin** [comment]
Yes, I do have some document templates : 
![image](https://user-images.githubusercontent.com/8756421/76708128-cb795000-66f4-11ea-9c3e-f04bb36b7c6c.png)

Also, I updated deps running `make deps` command.
The only thing I got from console are these warnings : 
![image](https://user-images.githubusercontent.com/8756421/76708148-ee0b6900-66f4-11ea-97cc-a38dca7410b6.png)

Here's a capture of me trying to pop the drop-down :
![DocumentVoucher](https://user-images.githubusercontent.com/8756421/76708268-ce287500-66f5-11ea-8d87-41eeaad91eba.gif)

**Comment by bobintetley** [comment]
Thanks. Well, that's got me scratching my head. The code used for the voucher docs was identical to the one used for the Receipt/Invoice button on the Payment tab - does that button work for you?

**Comment by julian-poidevin** [comment]
Yes, it does work on the Payement tab : 
![PaiementDocument](https://user-images.githubusercontent.com/8756421/76708402-c7e6c880-66f6-11ea-9705-79e32d033d20.gif)

**Comment by bobintetley** [comment]
Sorry. I've found the issue and it was occurring for me too - I'd done all the testing via Financial->Voucher Book. The backend wasn't sending the template list to the person_vouchers screen. There's a commit/fix  about to land now...

**Comment by julian-poidevin** [comment]
Perfect, thanks a lot !

**Comment by bobintetley** [comment]
No, thank you!
