### ISSUE TITLE
POT file generation may be inaccurate

### ISSUE THREAD

**Issue by julian-poidevin** [bobintetley/asm3#752]
Hello,

I've been translating ASM in french for a few month now and I've always wondered why there was still some parts of the app not translated at all whereas it seemed to appear in po file.

Here's some weird things I noticed :

### 1 - English po translation files has more entries than the French file
Here's a comparison using Poedit software : 

| `en_GB.po`  | `fr.po`  | `asm.pot` |
|---|---|---|
|  ![image](https://user-images.githubusercontent.com/8756421/77801666-94eaf000-7079-11ea-9ae9-6020de4bb61c.png)  | ![image](https://user-images.githubusercontent.com/8756421/77801651-8a305b00-7079-11ea-8837-24130787d6da.png) | ![image](https://user-images.githubusercontent.com/8756421/77801751-c1067100-7079-11ea-96b5-fb5d45224648.png) |

After using the "Catalog ➡️ Update from POT file" menu in Poedit, here's the result for the `fr.po` file

| `fr.po`  |
|---|
| ![image](https://user-images.githubusercontent.com/8756421/77801868-fd39d180-7079-11ea-9c2c-18cb625f6ff3.png) | 

Using this method, some parts of the app are not translated : 
![image](https://user-images.githubusercontent.com/8756421/77802513-51918100-707b-11ea-8863-25ac5a0d9466.png)

### 2 - Updating to POT file corrupt good setup
When having a good setup with every part of the software translated, if updating the translation with `asm.po`, it corrupts it and we get parts non translated again.

### 3 - Regenerating asm.pot with an other method saved the problem.
I managed to fix this issue by using [this method on StackOverflow](https://stackoverflow.com/a/44705132)

When converting en_GB.po into a POT file and updating `fr.po` with it, this works fine and all software parts are being translated correctly.

Here's the app correctly translated : 
![image](https://user-images.githubusercontent.com/8756421/77802818-fe6bfe00-707b-11ea-9635-e17e6edc8219.png)

-----------

I'm of course using `make translation` before each compilation. Do you think there could be a problem with the `make pot` command ? 

Here's a ZIP file with OLD & NEW po and pot files, this might help you out : [ASM-PO-DEBUG.zip](https://github.com/bobintetley/asm3/files/4396053/ASM-PO-DEBUG.zip)

Thanks

**Comment by bobintetley** [comment]
make pot is only supposed to update the pot file, it's upto the language translators tool to update their po file from it. 

make pot calls po/extract_strings.py to generate the pot. I wrote it, because I had trouble with xgettext missing things.

I think we need to identify if there's actually a problem - some of the language translation files will still have redundant translations for strings no longer in the program, where the pot file will not. To save me trying to figure it out, do you have some examples of strings that are not in the pot but should be?

**Comment by bobintetley** [comment]
sorry, I just noticed that you gave an example in the body, I'll have a look

**Comment by bobintetley** [comment]
when I restructured the code to put most of it an asm3 package, the pot extractor was not updated with the new location - it was not scanning most of the python code! Thanks again for the save.

**Comment by julian-poidevin** [comment]
Oh ! This explains why the non translated parts were grouped in the same places (timeline, menus ...). This explains the issues I had in #710 

So I was not crazy, happy to help out. 😁
