### ISSUE TITLE
signed/unsigned are reserved words in MySQL

### ISSUE THREAD

**Issue by julian-poidevin** [bobintetley/asm3#798]
Hello,

After merging the last changes of ASM master branch to my server I'm having the following issue :

```
<class '_mysql_exceptions.ProgrammingError'> at /main
(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'unsigned,
(SELECT COUNT(*) FROM log WHERE LinkType=1 AND Date >= '2020-04-20 00:' at line 1") 

Python	/usr/lib/sheltermanager3/asm3/dbms/base.py in query, line 571
Web	GET http://asm3.mceasso.fr:5000/main
```

I attached the html page in the ZIP below

[ErrorASMMainPage.zip](https://github.com/bobintetley/asm3/files/4541317/ErrorASMMainPage.zip)

Is it related to the MySQL version I'm using ?

Thanks

**Comment by bobintetley** [comment]
I should do more testing with MySQL I guess. I think the fault is that the alias I'm using "unsigned" is a keyword in MySQL and not SQLite or PostgreSQL. Try this commit ...

**Comment by julian-poidevin** [comment]
Thanks a lot @bobintetley for your reactivity. This is fixed !
