### ISSUE TITLE
<<AppointmentTime>> wordkey is showing seconds

### ISSUE THREAD

**Issue by julian-poidevin** [bobintetley/asm3#806]
Using the `AppointmentTime` wordkey in our documents, it's displaying seconds : 

![image](https://user-images.githubusercontent.com/8756421/80605945-fcf37400-8a33-11ea-95a4-9eb3b99fcb7a.png)

I don't think it should be displaying seconds, this does not really make sense.
Maybe other wordkeys are affected.

**Comment by bobintetley** [comment]
fixed by #808
