### ISSUE TITLE
Online Form can't be submitted if having a mandatory field unfilled not displayed (show if condition)

### ISSUE THREAD

**Issue by julian-poidevin** [bobintetley/asm3#819]
I had an issue with an online form where it could not be submitted (and not showing any error message) if a field with a "Show If" condition was not shown and was mandatory.

I think it is easily reproducible but if you need any input from me, please let me know.

**Comment by bobintetley** [comment]
that was already fixed a few days ago in this commit: https://github.com/bobintetley/asm3/commit/177622c2da9227ccc08eff6a18085f439e9aeb84

**Comment by julian-poidevin** [comment]
Oh, I'm sorry, I looked into issues on Github and didn't find one.
I didn't think about looking into commits.

Also my ASM version was not up-to-date, that's why I had this issue.

**Comment by bobintetley** [comment]
no problem, thanks for checking!
