### ISSUE TITLE
Paypal CSV Import not Working

### ISSUE THREAD

**Issue by shaneherman** [bobintetley/asm3#826]
**Issue:** Paypal Activity Import stopped working. 

**Receiving this Error:**
This CSV file does not look like a PayPal CSV (missing Date)

See attach example CSV transaction. <To Test>

Please advise on how to fix. We have never had issue with importing from Paypal Activity Report.
[Paypal-Download-2.CSV.TXT](https://github.com/bobintetley/asm3/files/4639238/Paypal-Download-2.CSV.TXT)

**Comment by bobintetley** [comment]
Your PayPal file is UTF-8 encoded where they usually send cp1252. This has caused the UTF8 Byte-Order-Marker to be prepended to the Date column, making it invisible. I've applied a fix now.

**Comment by shaneherman** [comment]
thank you.
