### ISSUE TITLE
Online forms : Data too long for column 'Flags' at row 1

### ISSUE THREAD

**Issue by julian-poidevin** [bobintetley/asm3#851]
I'm having applicants reporting me errors when validating this online form : http://mceasso.fr/formulaire-adoptions

Here's the following error log when submitting the online form (sorry phone capture for now I don't have access to a PC) 
![IMG_20200608_183144](https://user-images.githubusercontent.com/8756421/84056678-d91e3900-a9b6-11ea-82cb-762b5c3fe726.jpg)

You'll be able to reproduce the issue if submitting the form. Let me know if you need any additional inputs

**Comment by julian-poidevin** [comment]
Here's the configuration :
![IMG_20200608_183818](https://user-images.githubusercontent.com/8756421/84057015-547fea80-a9b7-11ea-8d87-0719cc904a96.jpg)

**Comment by bobintetley** [comment]
That doesn't look like it should be a problem. The max length is 767-1024 chars on MySQL depending on collation.

Maybe you put long text in the flags field on the check boxes in your form? Check boxes can be used to set custom flags, so if you put other text in the flags field it would be copied to the flags field when those boxes are checked and might be causing the problem? Have a look at the definitions of your checkboxes.

**Comment by julian-poidevin** [comment]
I don't know if this is linked but we were never able to received submissions by email for this specific online form (it works for other forms)

**Comment by julian-poidevin** [comment]
> That doesn't look like it should be a problem. The max length is 767-1024 chars on MySQL depending on collation.
> 
> Maybe you put long text in the flags field on the check boxes in your form? Check boxes can be used to set custom flags, so if you put other text in the flags field it would be copied to the flags field when those boxes are checked and might be causing the problem? Have a look at the definitions of your checkboxes.

Ok thanks I'll check that

**Comment by julian-poidevin** [comment]
All solved ! Email and error. I mistakenly used the flag box as a "Tip" box to give additional details and put a very long text 
. Thanks a lot.
