### ISSUE TITLE
dbupdate fails when going to v43

### ISSUE THREAD

**Issue by inghamn** [bobintetley/asm3#854]
The automated dbupdate fails when attempting to create the v_ownerdonation view.  "owneraddress specified more than once".  I don't know if this is a problem with the dbupdate code, or an SQL problem with the desired new view.

I am working on upgrading our ASM install from v43u to the v43 release.  We have been running a version checked out from the master branch on 2019-10-09

I used the tarball from the release:
https://github.com/bobintetley/asm3/archive/43.tar.gz

This is on a new Ubuntu 20.04 server with Postgres 12, using python3.
[error.log](https://github.com/bobintetley/asm3/files/4754545/error.log)

**Comment by bobintetley** [comment]
I think this was fixed immediately after release, but I guess I didn't apply the fix to the release. 

None of the views are actually used by the software, they're only there as a convenience for report writers and the error can be ignored. If you want to patch it in your copy, the fault is in financial.py/get_donation_query - OwnerAddress appears in the list twice and one of them can be removed.

**Comment by inghamn** [comment]
Much obliged.  That explains why I wasn't able to find the problem when I was reading through the master branch
