### ISSUE TITLE
Available Dogs Not Pulling Correctly on Website

### ISSUE THREAD

**Issue by Katrinamp** [bobintetley/asm3#86]
Hello there, 
It looks like our available dogs page, which pulls from ASM, is suddenly not working correctly. Is the system experiencing issues? You can view the page here: http://www.helpinghoundsdogrescue.org/adopt/

**Comment by bobintetley** [comment]
It's a fault with the overnight batch on the server and not a program bug. We've applied a fix now, but if you run your publisher manually from Publishing->Publish via HTML/FTP in the meantime it will update your site.
