### ISSUE TITLE
Online form: disable submit

### ISSUE THREAD

**Issue by bobintetley** [bobintetley/asm3#897]
A few people complaining that their users mash the submit button like mad then get the flood protection error even though the first submit worked, so they wait and do it again.

Disable the submit button on click. The only issue I can see is that we use the HTML5 required attribute so we need to be able to re-enable it again if that validation fails.

**Comment by julian-poidevin** [comment]
Hello,

Starting from this commit, my forms won't submit from HTML5 browser (tried Chrome and Edge). It works on the old Internet Explorer though.

I tried to run make test to see if any error message pops out but nothing... I also tried to see the chrome console in dev tools but nothing shows up.

What can I provide to help you diagnosis the problem ? Don't you have any other people reporting the issue ? 🤔 

Thanks !

**Comment by bobintetley** [comment]
It's only just gone live. Thanks for the heads up, I'll do some more testing.

The change is supposed to disable the button and then re-enable it if any validation fails.

**Comment by julian-poidevin** [comment]
Oh ok, I thought the code was directly going live.

**Comment by bobintetley** [comment]
No, not always. The fix is committing now. Looks like the problem is that if you disable a submit button on its click event, Chrome's default event handler then won't submit the form so you have to do it yourself. Shows that I do most of my testing on Firefox :-)

**Comment by julian-poidevin** [comment]
Works like a charm ! Thanks !
