### ISSUE TITLE
Possible Data Leak through Signing form

### ISSUE THREAD

**Issue by beeranddogs** [bobintetley/asm3#917]
Hi,

One of my development team found an issue where he took the URL of a document signature request and was able to access other submitted forms by changing the number at the end of the URL. Obviously, this is a possible vulnerability as someone could access the information of other applicants for adoption.

**Comment by bobintetley** [comment]
Thanks for reporting this. Yes, that service call should require two pieces of matching information to prevent people incrementing the number looking for other documents.
