### ISSUE TITLE
Can't set DB_DECODE_HTML_ENTITIES = True

### ISSUE THREAD

**Issue by grousso** [bobintetley/asm3#94]
When DB_DECODE_HTML_ENTITIES = True

then error

 s = MySQLdb.escape_string(s)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)

Best Regards

Geroge

**Comment by bobintetley** [comment]
Is your MySQL database using a UTF8 collation/sort? If it's using a Greek codepage or something it might cause this. Also, DB_DECODE_HTML_ENTITIES is actually a massive XSS hole, so it's very unwise to set it to true for security reasons - I think rather than trying to fix it we should be removing it altogether. We don't use it on sheltermanager.com

**Comment by grousso** [comment]
When i create the database its utf8 and utf8_general_ci
At asm instalation its greek database

Lets go 2 years back :)
23/7/2014
Hello from Greece
The greek characters stored at the database at 5bits format and this is a problem.
Please there is a solution for that?
Have a nice day and thanks a lot for the amazing software.

And your answer was
Hi, ASM does store unicode characters as HTML entities. There
isn't currently a fix, but the solution would lie in fixing the
db.ds method to call utils.html_decode to turn the HTML
entities back into unicode characters before storing in the
database.

It is something we have a ticket on Launchpad to look at this
release.





So if you will remove the decoder is something i can do to not store 5 digits format at the database?
![screenshot 2014-07-23 09 22 14-1](https://cloud.githubusercontent.com/assets/9210894/20894029/95e61f5e-bb1c-11e6-877e-dddaab7c611c.png)

**Comment by bobintetley** [comment]
You're right, I don't know why this has broken for you, but there is a very simple fix. 

Open the file db.py, find the def escape(s) function and change s = MySQLdb.escape_string(s) to just the word "pass" instead and save, then restart your ASM service.

**Comment by grousso** [comment]
Unfortunately this fix is not working

I donwload the last commit and its the same with and without replacing the "s = MySQLdb.escape_string(s)" with the word "pass"

Best Regards George

![screenshot from 2017-01-10 11-52-53](https://cloud.githubusercontent.com/assets/9210894/21801785/d4ab4112-d72b-11e6-84ae-b33b611c7d32.png)
![screenshot from 2017-01-10 11-53-35](https://cloud.githubusercontent.com/assets/9210894/21801784/d4aa3eac-d72b-11e6-976f-fa1e61a8552c.png)
![screenshot from 2017-01-10 11-55-30](https://cloud.githubusercontent.com/assets/9210894/21801786/d4b0cc18-d72b-11e6-99aa-1ec26a18522a.png)

**Comment by bobintetley** [comment]
The fix I gave you to do manually conflicted with the fix I commited to source control. I've tested with MySQL and can confirm the bug is definitely fixed now. The problem was caused by the MySQLdb.escape_string function requiring UTF-8 input, but once we've done with it we need to decode that UTF-8 back to Unicode before continuing or you get the error you saw. Thanks for persisting with this, if you do a pull from git to get the latest db.py it should be ok now.

**Comment by grousso** [comment]
It remains :(
It store greek chars to 5bits format again
![screenshot from 2017-01-10 16-53-41](https://cloud.githubusercontent.com/assets/9210894/21810665/62153340-d755-11e6-8721-e49eaa8137c1.png)

**Comment by bobintetley** [comment]
I'm not sure what to suggest - in my local tests it's now working for unicode chars when I save with DB_DECODE_HTML_ENTITIES set to True. The fix only affects new saves, but I guess you knew that already? Have you checked that DB_DECODE_HTML_ENTITIES is True in sitedefs?

**Comment by grousso** [comment]
I thought that this solution wasn't connected with DB_DECODE_HTML_ENTITIES because you said that is risky to use it due to security issues and when I used to set it to True, the application was crashing with the error:
s = MySQLdb.escape_string(s)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)

So I put it to True and everything is OK. I have Greek chars in database and no Html entities any more. 
Thanks a lot,  I will continue to report issues. 
Best Regards 
George
