### ISSUE TITLE
warn: no smcom_client

### ISSUE THREAD

**Issue by grousso** [bobintetley/asm3#95]
After
# python2.7 /var/www/html/40.src/cron.py all
All jobs are working but it gives me:
warn: no smcom_client

Best Regards

**Comment by grousso** [comment]
From jobs = All jobs :)
Good morning from Greece

**Comment by bobintetley** [comment]
This is normal behaviour and the warning can be ignored. It's just warning that the hooks for sheltermanager.com services aren't available - which they won't be for a normal open source install.
