### ISSUE TITLE
Reports Using $$Group not Parsing correctly

### ISSUE THREAD

**Issue by drchardson** [bobintetley/asm3#953]
We have an issue where we want to Display the number of each type of animal and group them according to SpeciesName. So Canine would have all dogs within a specified date range under one table and report would list all Species with the above attached.
The problem is the report repeats the Species Name Canine multiple times rather than list it once with all the canines in that group.
![image](https://user-images.githubusercontent.com/12817627/105438814-54bcb580-5c29-11eb-90f7-07cb235b5574.png)
![image](https://user-images.githubusercontent.com/12817627/105438829-5edeb400-5c29-11eb-836c-40bf27b1e751.png)

**Comment by bobintetley** [comment]
You need to ORDER your sql results by column grouping Eg: ORDER BY SpeciesID. This is not a bug.

If you want the species names output in alphabetical order, you should order and group on SpeciesName rather than SpeciesID.
