### ISSUE TITLE
HTML entities in publish Publishing Options

### ISSUE THREAD

**Issue by grousso** [bobintetley/asm3#96]
![asm issue 3](https://cloud.githubusercontent.com/assets/9210894/20878411/6f7e8b20-bad7-11e6-83a5-784aa4df242f.JPG)

"Add this text to all animal descriptions" field is full of HTML entities instead of plain text (greek language)

Best Regards

**Comment by bobintetley** [comment]
is this the 39 release or the latest 40u from source control? I think we might have already fixed this.

**Comment by grousso** [comment]
40u

**Comment by bobintetley** [comment]
does re-entering the text and saving it fix this problem after the db.py change I recommended on your other issue?

**Comment by grousso** [comment]
Unfortunately not, neither of them are ok.
Please see the screenshots i posted to the other issue.

**Comment by bobintetley** [comment]
Thanks for persisting, the problem was with display of loaded config items on that screen, rather than database storage. I've committed a fix now to publish_options.js. Please pull the latest from git. Can confirm I've tested and fixed.

**Comment by grousso** [comment]
Yes its working, thank you.

But the other remains
